import { useMemo, useState } from 'react'
import { Modal } from '@/components/ui/Modal'
import { generateQrSvg, isQrTextSupported } from '@/lib/qr'

interface QrShareProps {
  /** Absolute URL the QR encodes (e.g. `${origin}/share/:token`). */
  url: string
  /** Filename stem for the downloaded SVG (defaults to "share-qr"). */
  filename?: string
}

/**
 * QR-share affordance for `<ShareModal />`. Renders a small SVG fallback
 * panel (see `lib/qr.ts` — full QR encoder is a TODO), a download button
 * and a "fullscreen" modal trigger so the user can scan with a phone.
 */
export function QrShare({ url, filename = 'share-qr' }: QrShareProps) {
  const [bigOpen, setBigOpen] = useState(false)
  const supported = isQrTextSupported(url)
  const small = useMemo(
    () => (supported ? generateQrSvg(url, 160) : null),
    [url, supported],
  )
  const big = useMemo(
    () => (supported ? generateQrSvg(url, 480) : null),
    [url, supported],
  )

  const handleDownload = () => {
    if (!small) return
    if (typeof window === 'undefined' || typeof document === 'undefined') return
    try {
      const blob = new Blob([generateQrSvg(url, 480)], { type: 'image/svg+xml' })
      const objUrl = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = objUrl
      a.download = `${filename}.svg`
      document.body.appendChild(a)
      a.click()
      a.remove()
      URL.revokeObjectURL(objUrl)
    } catch {
      /* download not available — silently no-op */
    }
  }

  if (!supported) {
    return (
      <div
        className="rounded border border-amber-200 bg-amber-50 px-3 py-2 text-[11px] text-amber-800"
        data-testid="qr-share-unsupported"
      >
        QR 생성 불가 — URL 길이가 허용 한도를 초과합니다.
      </div>
    )
  }

  return (
    <div
      className="flex items-start gap-3 rounded border border-gray-200 bg-white p-2 dark:border-gray-800 dark:bg-gray-900"
      data-testid="qr-share"
    >
      <div
        className="shrink-0"
        // The SVG is generated by a pure function in `lib/qr.ts`; the URL is
        // XML-escaped by the encoder so this is safe.
        dangerouslySetInnerHTML={{ __html: small! }}
      />
      <div className="flex flex-1 flex-col gap-1.5 text-[11px]">
        <p className="text-gray-700 dark:text-gray-300">
          모바일에서 스캔해 바로 열 수 있습니다.
        </p>
        <div className="flex flex-wrap gap-1.5">
          <button
            type="button"
            onClick={handleDownload}
            data-testid="qr-share-download"
            className="h-6 rounded border border-gray-300 bg-white px-2 text-[11px] text-gray-700 hover:bg-gray-50 dark:border-gray-700 dark:bg-gray-900 dark:text-gray-200 dark:hover:bg-gray-800"
          >
            QR 다운로드
          </button>
          <button
            type="button"
            onClick={() => setBigOpen(true)}
            data-testid="qr-share-bigview"
            className="h-6 rounded border border-gray-300 bg-white px-2 text-[11px] text-gray-700 hover:bg-gray-50 dark:border-gray-700 dark:bg-gray-900 dark:text-gray-200 dark:hover:bg-gray-800"
          >
            큰 화면으로 보기
          </button>
        </div>
      </div>
      {bigOpen && (
        <Modal
          open={bigOpen}
          onClose={() => setBigOpen(false)}
          title="QR 코드"
          size="md"
        >
          <div
            className="flex flex-col items-center gap-3 p-5"
            data-testid="qr-share-big-panel"
          >
            <div dangerouslySetInnerHTML={{ __html: big! }} />
            <p className="break-all text-center text-xs text-gray-600 dark:text-gray-400">
              {url}
            </p>
            <p className="text-[11px] text-gray-500">
              휴대폰 카메라로 스캔하세요.
            </p>
          </div>
        </Modal>
      )}
    </div>
  )
}
