# generated by datamodel-codegen:
#   filename:  document.json

from __future__ import annotations

from enum import Enum, IntEnum
from typing import Any, Literal, Annotated

from pydantic import AnyUrl, BaseModel, ConfigDict, Field, RootModel, model_validator


class Ulid(RootModel[str]):
    root: str = Field(..., pattern='^[0-9A-HJKMNP-TV-Z]{26}$')
    """
    Crockford base32 ULID
    """


class ImageRef(RootModel[str]):
    root: str = Field(
        ...,
        pattern='^(?:[0-9A-HJKMNP-TV-Z]{26}|[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})$',
    )
    """
    FK to images.id — accepts ULID (legacy seed data) or UUID (uploaded images)
    """


class Slug(RootModel[str]):
    root: str = Field(
        ..., pattern='^[a-z0-9\\uAC00-\\uD7A3][a-z0-9\\uAC00-\\uD7A3-]{0,99}$'
    )
    """
    url-safe identifier (lowercase ASCII, digits, hyphen, Hangul)
    """


class Confidentiality(Enum):
    public = 'public'
    internal = 'internal'
    restricted = 'restricted'


class DocumentMeta(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    division: str = Field(..., min_length=1)
    team: str | None = None
    group: str | None = None
    part: str | None = None
    owners: list[str] = Field(..., min_length=1)
    reviewers: list[str] | None = []
    tags: list[str] = []
    category: str | None = None
    confidentiality: Confidentiality


class Badge(Enum):
    """
    배경/텍스트 컬러로 강조하는 뱃지 종류. neutral=회색.
    """

    success = 'success'
    info = 'info'
    warn = 'warn'
    danger = 'danger'
    neutral = 'neutral'


class InfoboxRich(BaseModel):
    """
    Richer Infobox value — wraps a label with optional link / badge / icon / color hints. Used wherever a plain string isn't enough (예: 상태 뱃지, 담당자 메일 링크).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    text: str
    """
    표시 텍스트.
    """
    href: str | None = None
    """
    링크 URL — 있으면 텍스트가 클릭 가능한 a 태그로 렌더링.
    """
    icon: str | None = None
    """
    선두 이모지 아이콘 (예: 📞 ✉️ 👤).
    """
    badge: Badge | None = None
    """
    배경/텍스트 컬러로 강조하는 뱃지 종류. neutral=회색.
    """
    color: str | None = Field(None, pattern='^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')
    """
    텍스트 색 직접 지정 (badge와 함께 쓰면 badge가 우선).
    """


class Layout(Enum):
    """
    Visual layout for this section's blocks. Drives both the wiki view (block arrangement inside the section) and presentation view (slide template). Defaults to 'stack' (existing behaviour: blocks render top-to-bottom). 'two-col' splits blocks alternately into two columns. 'image-left'/'image-right' put the first ImageBlock on one side and remaining blocks on the other. 'title-only' renders just the section heading (PPT cover style). 'full-bleed' uses the first ImageBlock as a full-width background with subsequent blocks overlaid.
    """

    stack = 'stack'
    two_col = 'two-col'
    image_left = 'image-left'
    image_right = 'image-right'
    title_only = 'title-only'
    full_bleed = 'full-bleed'


class LayoutWidth(RootModel[float]):
    root: float = Field(..., ge=10.0, le=90.0)


class Align(Enum):
    left = 'left'
    center = 'center'
    right = 'right'
    full = 'full'


class Permission(Enum):
    all = 'all'
    editor = 'editor'
    admin = 'admin'


class Level(Enum):
    """
    Heading 블록(heading-4 type)에서 실제 보여줄 단계. 2=큰 제목, 3=중간 제목, 4=작은 제목(기본). 다른 블록 타입에서는 무시됨.
    """

    int_2 = 2
    int_3 = 3
    int_4 = 4


class Audience(Enum):
    """
    이 블록이 노출되는 뷰. 'both'(기본): 위키 + 슬라이드 둘 다. 'wiki-only': 위키에만 (프레젠테이션에서 숨김). 'slide-only': 프레젠테이션에서만 (위키 본문에서는 숨김). 발표용 큰 이미지/스피커 멘트, 또는 위키엔 자세히 적고 슬라이드엔 빼고 싶은 표 등을 분리할 때 사용.
    """

    both = 'both'
    wiki_only = 'wiki-only'
    slide_only = 'slide-only'


class SlideBreak(Enum):
    """
    프레젠테이션 모드에서 사용자가 명시적으로 슬라이드 분할 지점을 지정. 'before': 이 블록부터 새 슬라이드 시작. 'after': 이 블록 다음부터 새 슬라이드 시작. buildSlides 의 자동 BUDGET 분할보다 우선. 같은 섹션 안에서 발표자 흐름을 직접 제어할 때 사용.
    """

    before = 'before'
    after = 'after'


class BlockMeta(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    align: Align | None = None
    collapsed: bool | None = None
    locked: bool | None = None
    permission: Permission | None = None
    note: str | None = None
    level: Level | None = None
    """
    Heading 블록(heading-4 type)에서 실제 보여줄 단계. 2=큰 제목, 3=중간 제목, 4=작은 제목(기본). 다른 블록 타입에서는 무시됨.
    """
    width: int | None = Field(None, ge=32, le=4000)
    """
    사용자 지정 블록 너비(px). 미지정 또는 0이면 부모 컨테이너에 맞춤(기존 동작).
    """
    height: int | None = Field(None, ge=32, le=4000)
    """
    사용자 지정 블록 높이(px). 미지정이면 콘텐츠 자동 높이(기존 동작).
    """
    audience: Audience | None = None
    """
    이 블록이 노출되는 뷰. 'both'(기본): 위키 + 슬라이드 둘 다. 'wiki-only': 위키에만 (프레젠테이션에서 숨김). 'slide-only': 프레젠테이션에서만 (위키 본문에서는 숨김). 발표용 큰 이미지/스피커 멘트, 또는 위키엔 자세히 적고 슬라이드엔 빼고 싶은 표 등을 분리할 때 사용.
    """
    slide_break: SlideBreak | None = Field(None, alias='slideBreak')
    """
    프레젠테이션 모드에서 사용자가 명시적으로 슬라이드 분할 지점을 지정. 'before': 이 블록부터 새 슬라이드 시작. 'after': 이 블록 다음부터 새 슬라이드 시작. buildSlides 의 자동 BUDGET 분할보다 우선. 같은 섹션 안에서 발표자 흐름을 직접 제어할 때 사용.
    """


class ParagraphBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['paragraph']
    id: Ulid
    text: str
    meta: BlockMeta | None = None


class Level1(Enum):
    """
    Visual heading level. Optional — defaults to 4 (smallest). Sub-section heading; the document outline still uses Section nodes for the canonical hierarchy.
    """

    int_2 = 2
    int_3 = 3
    int_4 = 4


class Heading4Block(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['heading-4']
    id: Ulid
    title: str = Field(..., max_length=200)
    level: Level1 | None = None
    """
    Visual heading level. Optional — defaults to 4 (smallest). Sub-section heading; the document outline still uses Section nodes for the canonical hierarchy.
    """
    meta: BlockMeta | None = None


class Style(Enum):
    bullet = 'bullet'
    number = 'number'
    check = 'check'


class Options(BaseModel):
    """
    표시 옵션. 모두 optional, default 동작은 ON.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    stripe: bool | None = True
    """
    행 단위 zebra-striping. false 일 때만 OFF — 옛 문서 (옵션 미지정) 는 ON 유지. 중첩 항목 (depth>=1) 은 stripe 미적용.
    """


class ListBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['list']
    id: Ulid
    style: Style
    items: list[str]
    options: Options | None = None
    """
    표시 옵션. 모두 optional, default 동작은 ON.
    """
    meta: BlockMeta | None = None


class QuoteBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['quote']
    id: Ulid
    text: str
    cite: str | None = None
    meta: BlockMeta | None = None


class Variant(Enum):
    info = 'info'
    warn = 'warn'
    danger = 'danger'
    tip = 'tip'


class CalloutBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['callout']
    id: Ulid
    variant: Variant
    title: str | None = None
    text: str
    meta: BlockMeta | None = None


class CodeBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['code']
    id: Ulid
    language: str
    code: str
    filename: str | None = None
    meta: BlockMeta | None = None


class Display(Enum):
    block = 'block'
    inline = 'inline'


class MathBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['math']
    id: Ulid
    expression: str
    """
    LaTeX (KaTeX 호환)
    """
    display: Display | None = Display.block
    meta: BlockMeta | None = None


class Align1(Enum):
    """
    Per-cell horizontal alignment override (wins over column default).
    """

    left = 'left'
    center = 'center'
    right = 'right'


class Align2(Enum):
    """
    Default cell alignment for this column. dtype=number|percent|currency auto-defaults to right when align is unset.
    """

    left = 'left'
    center = 'center'
    right = 'right'


class Dtype(Enum):
    """
    Column data type. Drives auto-formatting and default alignment.
    """

    text = 'text'
    number = 'number'
    percent = 'percent'
    currency = 'currency'
    date = 'date'


class Column(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    width: str | None = None
    """
    CSS width — '120px' or '15%' or 'auto'.
    """
    align: Align2 | None = None
    """
    Default cell alignment for this column. dtype=number|percent|currency auto-defaults to right when align is unset.
    """
    dtype: Dtype | None = None
    """
    Column data type. Drives auto-formatting and default alignment.
    """
    format: str | None = None
    """
    Format hint. number/percent: decimal places like '2'. currency: ISO code or symbol like 'KRW' / '$'. date: pattern like 'YYYY-MM-DD'.
    """


class Aggregate(Enum):
    field_ = ''
    sum = 'sum'
    avg = 'avg'
    count = 'count'
    min = 'min'
    max = 'max'


class Footer(BaseModel):
    """
    Optional footer row showing per-column aggregates. Computed at render time from `rows` (flat mode) — sparse mode is skipped because merged-cell semantics make column-wise sums ambiguous.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    show: bool | None = None
    label: str | None = None
    """
    Label shown in the first column when no aggregate is set there.
    """
    aggregates: list[Aggregate] | None = None
    """
    Per-column aggregate. '' (empty) skips that column.
    """


class Density(Enum):
    """
    Row padding density. Default 'normal'.
    """

    compact = 'compact'
    normal = 'normal'
    comfortable = 'comfortable'


class BorderStyle(Enum):
    """
    Cell border style. Default 'horizontal'.
    """

    none = 'none'
    horizontal = 'horizontal'
    all = 'all'


class Column1(RootModel[int]):
    root: int = Field(..., ge=0)
    """
    Column scope: header text (string) or 0-based index (integer); omit to match every column.
    """


class Operator(Enum):
    gt = 'gt'
    gte = 'gte'
    lt = 'lt'
    lte = 'lte'
    eq = 'eq'
    neq = 'neq'
    between = 'between'
    top_n = 'top_n'
    bottom_n = 'bottom_n'
    contains = 'contains'
    not_contains = 'not_contains'


class Value(RootModel[list[float]]):
    root: list[float] = Field(..., max_length=2, min_length=2)
    """
    Numeric/string for comparison ops; [min, max] for between; N for top_n/bottom_n.
    """


class Style1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    bg: str | None = Field(None, pattern='^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')
    fg: str | None = Field(None, pattern='^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')
    bold: bool | None = None


class ConditionalFormattingItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    column: str | Column1 | None = None
    """
    Column scope: header text (string) or 0-based index (integer); omit to match every column.
    """
    operator: Operator
    value: float | str | Value
    """
    Numeric/string for comparison ops; [min, max] for between; N for top_n/bottom_n.
    """
    style: Style1


class Options1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    sortable: bool | None = None
    """
    Header click sorts asc/desc by that column (flat mode only).
    """
    searchable: bool | None = None
    """
    Show a search box above the table that filters rows (flat mode only).
    """
    density: Density | None = None
    """
    Row padding density. Default 'normal'.
    """
    sticky_first_col: bool | None = Field(None, alias='stickyFirstCol')
    """
    Pin the first column when the table scrolls horizontally.
    """
    row_numbers: bool | None = Field(None, alias='rowNumbers')
    """
    Show 1-based row numbers in a leading column.
    """
    stripe: bool | None = None
    """
    Zebra-striped rows. Default true; set false to disable.
    """
    border_style: BorderStyle | None = Field(None, alias='borderStyle')
    """
    Cell border style. Default 'horizontal'.
    """
    conditional_formatting: list[ConditionalFormattingItem] | None = Field(
        None, alias='conditionalFormatting'
    )
    """
    FE-only conditional formatting rules (WIDGET-02 Phase 1). Each rule scopes to a column (by header name or 0-based index; omit for all columns), tests cellValue with an operator, and applies a style. Sparse `cells[].bg/color/bold` always override. Not yet round-tripped through docx export.
    """


class Trend(Enum):
    up = 'up'
    down = 'down'
    flat = 'flat'


class Kind(Enum):
    """
    line=경향선, bar=막대, win-loss=양/음 1px 막대.
    """

    line = 'line'
    bar = 'bar'
    win_loss = 'win-loss'


class Sparkline(BaseModel):
    """
    Excel Insert→Sparkline 동등. 카드 하단의 작은 인-카드 차트.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    values: list[float]
    """
    시계열 값. 빈 배열이면 sparkline 미렌더.
    """
    kind: Kind | None = Kind.line
    """
    line=경향선, bar=막대, win-loss=양/음 1px 막대.
    """
    color: str | None = None
    """
    Sparkline 색 override. 미지정이면 trend 색 (▲↗ emerald / ▼↘ red / → gray) 또는 currentColor 사용. line=stroke, bar=fill, win-loss=양수 fill (음수는 같은 색 + opacity 0.55).
    """
    palette: list[str] | None = None
    """
    bar kind 전용 — 막대별 색 cycle. i 번째 막대는 palette[i % palette.length] 사용. line/win-loss 에서는 무시 (color 사용). 둘 다 지정되면 palette 우선.
    """


class Item(BaseModel):
    label: str
    value: str | float
    delta: str | float | None = None
    trend: Trend | None = None
    sparkline: Sparkline | None = None
    """
    Excel Insert→Sparkline 동등. 카드 하단의 작은 인-카드 차트.
    """


class Options2(BaseModel):
    """
    표시 옵션. 모두 optional, default 동작은 ON.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    stripe: bool | None = True
    """
    카드 단위 zebra-striping (`:nth-of-type(2n)`). grid 컬럼 수와 무관 — 카드 한 칸 건너 한 칸 음영.
    """


class KpiCardsBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['kpi-cards']
    id: Ulid
    items: list[Item]
    options: Options2 | None = None
    """
    표시 옵션. 모두 optional, default 동작은 ON.
    """
    meta: BlockMeta | None = None


class ChartType(Enum):
    """
    차트 타입. 'xy-line' 은 시리즈마다 자유로운 (x, y) 쌍 — labels 공유 안 함. 두 stress-strain 곡선처럼 시료별 측정점이 다른 데이터를 한 그림에 겹쳐 비교할 때 사용. data.labels 는 무시되고 각 series 의 points: [{x, y}] 가 그려진다. 'boxplot' 은 분포 비교용 — 시리즈마다 한 박스. raw mode (기본) 는 values:number[] 에서 min/Q1/median/Q3/max 자동 계산. precomputed mode (block.options.boxplotMode='precomputed') 는 values:[min, Q1, median, Q3, max] (length=5) 로 직접 지정.
    """

    line = 'line'
    bar = 'bar'
    pie = 'pie'
    area = 'area'
    radar = 'radar'
    scatter = 'scatter'
    xy_line = 'xy-line'
    boxplot = 'boxplot'


class Engine(Enum):
    """
    Chart renderer. Default 'recharts' for back-compat; choose 'echarts' for rich interactivity (markPoint / markArea / brush / dataZoom).
    """

    recharts = 'recharts'
    echarts = 'echarts'


class Point(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    x: float
    y: float
    err: float | None = None
    """
    대칭 오차 (y±err). P3 추가.
    """
    err_low: float | None = Field(None, alias='errLow')
    """
    비대칭 오차 — 하한 (y - errLow ~ y).
    """
    err_high: float | None = Field(None, alias='errHigh')
    """
    비대칭 오차 — 상한 (y ~ y + errHigh).
    """


class YAxisIndex(IntEnum):
    """
    이 시리즈가 그려질 y 축. 0 (기본) = 왼쪽 축, 1 = 오른쪽 축. dual-axis 일 때 단위가 다른 두 시리즈를 같은 차트에 표시.
    """

    integer_0 = 0
    integer_1 = 1


class Series(BaseModel):
    name: str
    values: list[float] | None = None
    """
    labels 와 동일 길이의 y 값. chartType=='xy-line' 이면 무시되고 points 사용.
    """
    points: list[Point] | None = None
    """
    자유 (x, y) 쌍. chartType=='xy-line' 에서 사용. 시리즈마다 x 가 다를 수 있어 stress-strain 곡선처럼 측정점이 다른 데이터 비교 가능. 각 점에 optional err (대칭 error bar y±err) 또는 errLow/errHigh (비대칭) 가능 — 측정 오차 시각화.
    """
    caption: str | None = None
    """
    시리즈 추가 설명 — hover/legend 에 표시. 캡션은 사용자가 paste 시 헤더에서 추출하거나 직접 입력.
    """
    y_axis_index: YAxisIndex | None = Field(None, alias='yAxisIndex')
    """
    이 시리즈가 그려질 y 축. 0 (기본) = 왼쪽 축, 1 = 오른쪽 축. dual-axis 일 때 단위가 다른 두 시리즈를 같은 차트에 표시.
    """
    color: str | None = None
    """
    시리즈 색상 override. 미지정 시 PALETTE 자동. CSS 색 (#RGB, rgb(), name).
    """


class XAxisType(Enum):
    """
    x 축 데이터 유형. 'time' 이면 unix ms 또는 ISO date 로 해석 (P3 — timestamp x). 미지정 = 'value' (숫자).
    """

    value = 'value'
    time = 'time'


class Data(BaseModel):
    labels: list[str]
    series: list[Series]
    x_axis_label: str | None = Field(None, alias='xAxisLabel')
    """
    x 축 라벨. xy-line 처럼 카테고리가 아닌 연속값일 때 의미. paste 의 'x' 헤더 컬럼명에서 자동 추출 가능.
    """
    y_axis_label: str | None = Field(None, alias='yAxisLabel')
    """
    y 축 라벨. paste 의 'y' 헤더 컬럼명에서 자동 추출 가능.
    """
    y_axis_label2: str | None = Field(None, alias='yAxisLabel2')
    """
    오른쪽 y 축 라벨 — dual-axis 일 때 (series 중 yAxisIndex=1 있을 때) 사용.
    """
    x_axis_type: XAxisType | None = Field(None, alias='xAxisType')
    """
    x 축 데이터 유형. 'time' 이면 unix ms 또는 ISO date 로 해석 (P3 — timestamp x). 미지정 = 'value' (숫자).
    """


class KeyPoint(BaseModel):
    label: str
    x_index: int = Field(..., alias='xIndex', ge=0)
    color: str | None = None


class Region(BaseModel):
    label: str
    x_from_index: int = Field(..., alias='xFromIndex', ge=0)
    x_to_index: int = Field(..., alias='xToIndex', ge=0)
    color: str | None = None


class Interactions(BaseModel):
    """
    Friendly knobs for ECharts interactivity that map onto markPoint / markArea / dataZoom without requiring users to write raw EChartsOption.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    key_points: list[KeyPoint] | None = Field(None, alias='keyPoints')
    """
    Highlighted points on the curve (label, x-index, optional color).
    """
    regions: list[Region] | None = None
    """
    Coloured x-range bands (e.g. Elastic / Plastic). xFromIndex / xToIndex are inclusive label indexes.
    """
    show_zoom: bool | None = Field(None, alias='showZoom')
    """
    Inline dataZoom slider under the chart.
    """
    show_crosshair: bool | None = Field(None, alias='showCrosshair')
    """
    Crosshair guides + axis pointers.
    """


class FitType(Enum):
    """
    피팅 모델. P1 은 linear 만, P3 에서 나머지.
    """

    linear = 'linear'
    poly2 = 'poly2'
    poly3 = 'poly3'
    exp = 'exp'
    power = 'power'


class FitRange(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    x_min: float = Field(..., alias='xMin')
    x_max: float = Field(..., alias='xMax')


class Sampling(Enum):
    none = 'none'
    lttb = 'lttb'


class Display1(BaseModel):
    """
    사용자 시각화 토글 상태. 차트 블록과 함께 저장되어 재방문 시 동일 상태 복원. P1 에서 gridOn/xLog/yLog/showFit + 자동 zoom 지원, P2 에서 fitRange/축범위/stats, P3 에서 fitType/도메인 옵션 확장.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    grid_on: bool | None = Field(None, alias='gridOn')
    """
    격자 표시 (기본 true).
    """
    x_log: bool | None = Field(None, alias='xLog')
    """
    x 축 log 스케일.
    """
    y_log: bool | None = Field(None, alias='yLog')
    """
    y 축 log 스케일.
    """
    show_fit: bool | None = Field(None, alias='showFit')
    """
    linear fit + R² markLine 표시.
    """
    x_min: float | None = Field(None, alias='xMin')
    x_max: float | None = Field(None, alias='xMax')
    y_min: float | None = Field(None, alias='yMin')
    y_max: float | None = Field(None, alias='yMax')
    fit_type: FitType | None = Field(None, alias='fitType')
    """
    피팅 모델. P1 은 linear 만, P3 에서 나머지.
    """
    fit_range: FitRange | None = Field(None, alias='fitRange')
    show_stats: bool | None = Field(None, alias='showStats')
    sampling: Sampling | None = None


class Annotations(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['marker']
    id: str
    x: float
    y: float
    label: str
    color: str | None = None


class Annotations1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['arrow']
    id: str
    from_x: float = Field(..., alias='fromX')
    from_y: float = Field(..., alias='fromY')
    to_x: float = Field(..., alias='toX')
    to_y: float = Field(..., alias='toY')
    label: str | None = None
    color: str | None = None


class Annotations2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['box']
    id: str
    x_min: float = Field(..., alias='xMin')
    x_max: float = Field(..., alias='xMax')
    y_min: float = Field(..., alias='yMin')
    y_max: float = Field(..., alias='yMax')
    label: str | None = None
    color: str | None = None


class ChartBlock(BaseModel):
    """
    Chart block — `engine` selects the renderer. 'recharts' (default) uses our existing simple chart UI; 'echarts' unlocks rich interaction (zoom, brush, hover slope, markPoint annotations, markArea regions). With 'echarts' the data fields below still drive the dataset, but `options` accepts any ECharts EChartsOption fragment that gets merged on top.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['chart']
    id: Ulid
    chart_type: ChartType = Field(..., alias='chartType')
    """
    차트 타입. 'xy-line' 은 시리즈마다 자유로운 (x, y) 쌍 — labels 공유 안 함. 두 stress-strain 곡선처럼 시료별 측정점이 다른 데이터를 한 그림에 겹쳐 비교할 때 사용. data.labels 는 무시되고 각 series 의 points: [{x, y}] 가 그려진다. 'boxplot' 은 분포 비교용 — 시리즈마다 한 박스. raw mode (기본) 는 values:number[] 에서 min/Q1/median/Q3/max 자동 계산. precomputed mode (block.options.boxplotMode='precomputed') 는 values:[min, Q1, median, Q3, max] (length=5) 로 직접 지정.
    """
    engine: Engine | None = None
    """
    Chart renderer. Default 'recharts' for back-compat; choose 'echarts' for rich interactivity (markPoint / markArea / brush / dataZoom).
    """
    title: str | None = None
    data: Data
    interactions: Interactions | None = None
    """
    Friendly knobs for ECharts interactivity that map onto markPoint / markArea / dataZoom without requiring users to write raw EChartsOption.
    """
    options: dict[str, Any] | None = None
    """
    Raw ECharts EChartsOption fragment, merged after `interactions` so power users can override anything.
    """
    display: Display1 | None = None
    """
    사용자 시각화 토글 상태. 차트 블록과 함께 저장되어 재방문 시 동일 상태 복원. P1 에서 gridOn/xLog/yLog/showFit + 자동 zoom 지원, P2 에서 fitRange/축범위/stats, P3 에서 fitType/도메인 옵션 확장.
    """
    annotations: list[Annotations | Annotations1 | Annotations2] | None = None
    """
    차트 위 도형 (P3) — 사용자가 데이터 좌표계에 직접 얹는 화살표/박스/마커/노트. ImageAnnotation 의 카운터파트이지만 좌표가 (x, y) 데이터 단위.
    """
    meta: BlockMeta | None = None


class Task(BaseModel):
    name: str
    start: str
    end: str
    progress: float | None = Field(None, ge=0.0, le=100.0)


class AxisUnit(Enum):
    """
    x-axis tick 단위. 미지정 시 'month'. tick 위치는 view 가 [minStart, maxEnd] 구간에서 해당 단위 경계마다 SVG `<line>` 으로 paint.
    """

    day = 'day'
    week = 'week'
    month = 'month'
    quarter = 'quarter'


class Options3(BaseModel):
    """
    표시 옵션. 모두 optional, default 동작은 ON.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    stripe: bool | None = True
    """
    task row 단위 zebra-striping (label 영역 포함 전체 행). SVG `<rect fill='#F9FAFB'>` 로 paint.
    """
    axis_unit: AxisUnit | None = Field('month', alias='axisUnit')
    """
    x-axis tick 단위. 미지정 시 'month'. tick 위치는 view 가 [minStart, maxEnd] 구간에서 해당 단위 경계마다 SVG `<line>` 으로 paint.
    """


class GanttBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['gantt']
    id: Ulid
    tasks: list[Task]
    options: Options3 | None = None
    """
    표시 옵션. 모두 optional, default 동작은 ON.
    """
    meta: BlockMeta | None = None


class Engine1(Enum):
    mermaid = 'mermaid'
    excalidraw = 'excalidraw'


class FlowBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['flow']
    id: Ulid
    engine: Engine1
    source: str
    """
    Mermaid DSL 또는 excalidraw JSON
    """
    meta: BlockMeta | None = None


class Layout1(Enum):
    tree = 'tree'
    horizontal = 'horizontal'


class OrgChartNode(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    label: str
    role: str | None = None
    children: list[OrgChartNode] | None = Field([], validate_default=True)


class IframeBlock1(BaseModel):
    """
    Embed an external page (`src`) OR an inline self-contained HTML document (`html`). Exactly one MUST be set. The renderer wraps the iframe in a sandbox boundary so the embed can't reach the parent DOM, cookies, or storage; only `allow-scripts` is granted so interactive embeds (charts, calculators) still work.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['iframe']
    id: Ulid
    src: AnyUrl
    """
    사내 화이트리스트 도메인만. `html` 와 동시 사용 금지.
    """
    html: str | None = Field(None, max_length=500000)
    """
    Self-contained HTML document. Rendered via iframe srcdoc + sandbox. Use this for ad-hoc interactive embeds (e.g. canvas-based charts) that don't need a hosting URL. `src` 와 동시 사용 금지.
    """
    title: str | None = None
    height: int | None = Field(None, ge=100, le=2000)
    meta: BlockMeta | None = None

    @model_validator(mode='after')
    def _reject_html_when_src(self):
        # XOR enforcement: src-branch must not also carry html.
        if self.html is not None:
            raise ValueError(
                'iframe block requires exactly one of `src` or `html`'
            )
        return self


class IframeBlock2(BaseModel):
    """
    Embed an external page (`src`) OR an inline self-contained HTML document (`html`). Exactly one MUST be set. The renderer wraps the iframe in a sandbox boundary so the embed can't reach the parent DOM, cookies, or storage; only `allow-scripts` is granted so interactive embeds (charts, calculators) still work.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['iframe']
    id: Ulid
    src: AnyUrl | None = None
    """
    사내 화이트리스트 도메인만. `html` 와 동시 사용 금지.
    """
    html: str = Field(..., max_length=500000)
    """
    Self-contained HTML document. Rendered via iframe srcdoc + sandbox. Use this for ad-hoc interactive embeds (e.g. canvas-based charts) that don't need a hosting URL. `src` 와 동시 사용 금지.
    """
    title: str | None = None
    height: int | None = Field(None, ge=100, le=2000)
    meta: BlockMeta | None = None

    @model_validator(mode='after')
    def _reject_src_when_html(self):
        # XOR enforcement: html-branch must not also carry src.
        if self.src is not None:
            raise ValueError(
                'iframe block requires exactly one of `src` or `html`'
            )
        return self


class IframeBlock(RootModel[IframeBlock1 | IframeBlock2]):
    root: IframeBlock1 | IframeBlock2
    """
    Embed an external page (`src`) OR an inline self-contained HTML document (`html`). Exactly one MUST be set. The renderer wraps the iframe in a sandbox boundary so the embed can't reach the parent DOM, cookies, or storage; only `allow-scripts` is granted so interactive embeds (charts, calculators) still work.
    """


class Provider(Enum):
    intra = 'intra'
    youtube = 'youtube'
    vimeo = 'vimeo'


class VideoBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['video']
    id: Ulid
    url: AnyUrl
    title: str | None = None
    provider: Provider | None = Provider.intra
    autoplay: bool | None = False
    """
    Auto-play on load. Browser autoplay policies may block this when muted=false; treat as a hint.
    """
    controls: bool | None = True
    """
    Show native video controls (play/pause/volume/seek).
    """
    loop: bool | None = False
    """
    Restart automatically when the video ends.
    """
    meta: BlockMeta | None = None


class Width(Enum):
    sm = 'sm'
    md = 'md'
    lg = 'lg'
    full = 'full'


class ImageBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['image']
    id: Ulid
    image_id: ImageRef = Field(..., alias='imageId')
    """
    FK to images.id (ULID or UUID)
    """
    caption: str | None = Field(None, max_length=500)
    alt: str | None = Field(None, max_length=200)
    width: Width | None = Width.md
    link: str | None = None
    """
    외부 URL 또는 위키 slug
    """
    meta: BlockMeta | None = None


class Layout2(Enum):
    grid = 'grid'
    carousel = 'carousel'


class Item1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    image_id: ImageRef = Field(..., alias='imageId')
    caption: str | None = Field(None, max_length=500)
    alt: str | None = Field(None, max_length=200)


class GalleryBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['gallery']
    id: Ulid
    layout: Layout2 = Layout2.grid
    items: list[Item1] = Field(..., min_length=1)
    meta: BlockMeta | None = None


class FileBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['file']
    id: Ulid
    file_id: Ulid = Field(..., alias='fileId')
    name: str
    size: int | None = Field(None, ge=0)
    mime: str | None = None
    meta: BlockMeta | None = None


class PdfBlock(BaseModel):
    # PDF-02 (block-audit c2): accept both `file_id` (snake; codegen
    # default) and `fileId` (camel; FE / docx round-trip) on input.
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    type: Literal['pdf']
    id: Ulid
    file_id: str = Field(..., alias='fileId')
    """
    FK to files table (mxwp-files); served via /api/v1/files/:file_id/download
    """
    title: str | None = None
    page: int | None = Field(1, ge=1)
    height_px: int | None = Field(600, ge=200, le=4000)
    meta: BlockMeta | None = None

    @model_validator(mode='before')
    @classmethod
    def _accept_either_file_id(cls, values: Any) -> Any:
        # Accept both `file_id` (snake) and `fileId` (camel) on
        # input. When both are present, `file_id` wins.
        if isinstance(values, dict):
            if 'file_id' not in values and 'fileId' in values:
                values['file_id'] = values['fileId']
        return values


class DocLinkCardBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['doc-link-card']
    id: Ulid
    slug: Slug
    show_summary: bool | None = Field(True, alias='showSummary')
    meta: BlockMeta | None = None


class GlossaryRefBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['glossary-ref']
    id: Ulid
    term: str
    meta: BlockMeta | None = None


class Width1(RootModel[float]):
    root: float = Field(..., ge=5.0, le=95.0)


class Kind1(Enum):
    image = 'image'
    table = 'table'
    chart = 'chart'


class Options4(BaseModel):
    """
    표시 옵션. 모두 optional, default 동작은 ON.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    stripe: bool | None = True
    """
    그룹별 <ol> 안에서 항목 단위 zebra-striping (각 그룹 내 카운터 리셋).
    """


class FigureIndexBlock(BaseModel):
    """
    Auto-generated table of figures (그림/표/차트 목차). The renderer walks the document and lists every captioned image, table (with caption), and chart (with title), each linked to its anchor. `kinds` controls which lists to render.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['figure-index']
    id: Ulid
    title: str | None = '그림 목차'
    kinds: list[Kind1] | None = Field(None, max_length=3, min_length=1)
    """
    Which figure types to include — 'image' (그림), 'table' (표), 'chart' (차트). Order in this array determines section order. Omit for all three.
    """
    options: Options4 | None = None
    """
    표시 옵션. 모두 optional, default 동작은 ON.
    """
    meta: BlockMeta | None = None


class Size(Enum):
    sm = 'sm'
    md = 'md'
    lg = 'lg'
    xl = 'xl'


class SpacerBlock(BaseModel):
    """
    Explicit vertical spacer. Default inter-block spacing is tight (8px). Insert a spacer block to add deliberate breathing room. `size` chooses the gap: sm=16px, md=32px (default), lg=64px, xl=128px.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['spacer']
    id: Ulid
    size: Size | None = Size.md
    meta: BlockMeta | None = None


class Kind2(Enum):
    inline = 'inline'
    csv = 'csv'


class Dtype1(Enum):
    number = 'number'
    string = 'string'
    date = 'date'


class FieldModel(BaseModel):
    name: str
    dtype: Dtype1


class Schema(BaseModel):
    """
    Optional — fields 자동 추론 가능하면 생략. 명시 시 우선.
    """

    fields: list[FieldModel] | None = None


class Source(BaseModel):
    """
    Inline / CSV source — rows[] 는 paste 시점에 저장.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Kind2
    rows: list[dict[str, str | float | None]]
    """
    Raw rows — each is a flat object of field→value. csv kind 이면 CSV text 도 inline 으로 paste 시점에 parse 후 저장.
    """
    schema_: Schema | None = Field(None, alias='schema')
    """
    Optional — fields 자동 추론 가능하면 생략. 명시 시 우선.
    """


class Source1(BaseModel):
    """
    Sprint 6 — 같은 문서 안 DataSourceBlock 결과를 raw rows 로 사용. viewer 가 DataSourceBlock 의 query 결과 (`{columns, rows}` 또는 `{data: [...]}`) 를 `Record<field, value>[]` 로 변환해 engine 에 넘긴다. async + 캐시는 TanStack Query 의 DataSourceBlock 쿼리를 그대로 재사용.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['data-source']
    data_source_id: Ulid = Field(..., alias='dataSourceId')
    """
    참조할 DataSourceBlock 의 id
    """


class Rows(RootModel[str]):
    root: str = Field(..., min_length=1)


class Group(Enum):
    """
    raw row 의 date 를 bucket 할 단위. year=YYYY, quarter=YYYY-Q1..4, month=YYYY-MM, week=YYYY-Www(ISO), day=YYYY-MM-DD. row[field] 가 ISO date string / epoch ms / Date 로 파싱 가능한 값이어야 함.
    """

    year = 'year'
    quarter = 'quarter'
    month = 'month'
    week = 'week'
    day = 'day'


class Rows1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field: str = Field(..., min_length=1)
    group: Group | None = None
    """
    raw row 의 date 를 bucket 할 단위. year=YYYY, quarter=YYYY-Q1..4, month=YYYY-MM, week=YYYY-Www(ISO), day=YYYY-MM-DD. row[field] 가 ISO date string / epoch ms / Date 로 파싱 가능한 값이어야 함.
    """


class Cols(RootModel[str]):
    root: str = Field(..., min_length=1)


class Group1(Enum):
    year = 'year'
    quarter = 'quarter'
    month = 'month'
    week = 'week'
    day = 'day'


class Cols1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field: str = Field(..., min_length=1)
    group: Group1 | None = None


class Agg(Enum):
    sum = 'sum'
    count = 'count'
    avg = 'avg'
    min = 'min'
    max = 'max'
    median = 'median'
    stdev = 'stdev'
    var = 'var'


class ShowAs(Enum):
    """
    Sprint 3 — 값 표시 방식. value=raw, pct_row=row total 대비 %, pct_col=col total 대비 %, pct_total=grand total 대비 %, running=row 안 col 순서 누적 합.
    """

    value = 'value'
    pct_row = 'pct_row'
    pct_col = 'pct_col'
    pct_total = 'pct_total'
    running = 'running'


class Value1(BaseModel):
    """
    Measure spec — 'field' 또는 'expr' 중 하나가 반드시 있어야 한다 (engine runtime 에서 검증). expr 가 있으면 field 는 무시.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    field: str | None = Field(None, min_length=1)
    expr: str | None = Field(None, min_length=1)
    """
    Sprint 4 — calculated field 식. 각 row 의 fields 를 식별자로 참조하는 산술식 (예: 'revenue - cost', 'profit / revenue * 100'). 지원 연산: + - * / 와 괄호. 평가 결과를 numeric 으로 모은 뒤 agg 적용 (sum/avg/...). 잘못된 식이거나 row 에 필드 없을 시 그 row 는 무시.
    """
    agg: Agg
    label: str | None = None
    """
    표시 이름; default = '{agg}({field})' 또는 '{agg}({expr})'
    """
    show_as: ShowAs | None = Field('value', alias='showAs')
    """
    Sprint 3 — 값 표시 방식. value=raw, pct_row=row total 대비 %, pct_col=col total 대비 %, pct_total=grand total 대비 %, running=row 안 col 순서 누적 합.
    """
    number_format: str | None = Field(None, alias='numberFormat')
    """
    Sprint 3 — viewer 포맷 패턴. 예: '#,##0.00' (thousands+2dp), '0.0%' (percent 1dp), '#,##0' (integer thousands). 미설정 시 default toLocaleString (≤4dp, trailing 0 strip).
    """


class Options5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    empty_cell: str | None = Field('-', alias='emptyCell')
    """
    default '-'
    """


class Totals(BaseModel):
    """
    Sprint 2 — subtotal/grand total 토글
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    grand: bool | None = None
    """
    row+col 교차 grand total cell
    """
    row: bool | None = None
    """
    각 row 마지막 col 에 row total
    """
    col: bool | None = None
    """
    각 col 마지막 row 에 col total
    """


class Axis(Enum):
    """
    어느 축에 추가할지
    """

    row = 'row'
    col = 'col'


class CalculatedItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    axis: Axis
    """
    어느 축에 추가할지
    """
    name: str = Field(..., min_length=1)
    """
    축 위 표시 라벨
    """
    formula: str = Field(..., min_length=1)
    """
    산술식. 같은 축 항목 라벨을 식별자로. 공백/한글 라벨은 백틱으로 감싸기: '`Jan` + `Feb` + `Mar`'.
    """


class Axis1(Enum):
    row = 'row'
    col = 'col'


class Order(Enum):
    asc = 'asc'
    desc = 'desc'


class Sort(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    axis: Axis1
    by: str
    """
    dimension 이름 또는 measure label
    """
    order: Order | None = Order.desc


class Op(Enum):
    in_ = 'in'
    not_in = 'not_in'
    gt = 'gt'
    lt = 'lt'
    between = 'between'
    top_n = 'top_n'
    bottom_n = 'bottom_n'


class Filter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field: str
    op: Op
    value: Any


class PivotTableBlock(BaseModel):
    """
    Pivot table widget — Excel pivot table 동등. raw rows 를 rows × cols × values 축으로 cross-tab 집계. Sprint 1 = inline source + 기본 집계 (sum/count/avg/min/max). Subtotal/grand total/sort/filter 는 Sprint 2, % of total / 누적 / numberFormat 은 Sprint 3 (measure.showAs + measure.numberFormat). Sprint 4 = calculated field (measure.expr — 'revenue - cost' 같은 식, formulaEngine 산술 subset 평가 후 agg).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['pivot-table']
    id: Ulid
    source: Source | Source1
    rows: list[Rows | Rows1]
    """
    Row 축 dimension field 이름 list (e.g., ['department', 'year']). Sprint 5 — 각 항목은 단순 field 이름 (문자열) 이거나 시간 자동 그룹을 위해 {field, group} object. group 은 'year'|'quarter'|'month'|'week'|'day' 중 하나로 raw row 의 date 를 bucket. 미명시 field 는 raw value 사용.
    """
    cols: list[Cols | Cols1]
    """
    Col 축 dimension field 이름 list. 빈 배열 = col 축 없음 (flat aggregation). rows 와 동일하게 시간 그룹 object 형식 허용.
    """
    values: list[Value1] = Field(..., min_length=1)
    """
    Measure(s) — Sprint 1 은 1개 이상.
    """
    options: Options5 | None = None
    totals: Totals | None = None
    """
    Sprint 2 — subtotal/grand total 토글
    """
    calculated_items: list[CalculatedItem] | None = Field(None, alias='calculatedItems')
    """
    Sprint 5 — 행/열 축 안 가상 항목 (e.g. 'Q1 = Jan + Feb + Mar'). 각 item 은 base aggregation 이 끝난 후 합성. formula 는 다른 같은-축 항목 라벨을 식별자로 참조하는 산술식 (+ - * / 와 괄호). 평가는 각 measure × (반대 축의 각 위치) 마다 한 번. base 항목과 라벨 충돌 시 calculated item 가 추가 (덮어쓰기 X).
    """
    sort: Sort | None = None
    filters: list[Filter] | None = None
    bound_slicers: list[Ulid] | None = Field(None, alias='boundSlicers')
    """
    Sprint 6 (G2) — listen 할 SlicerBlock id 목록. viewer 가 hydration 단계에서 각 slicer 의 active values 를 filter (`{field, op:'in', value: [...]}`) 로 변환해 기존 filters 에 concat. slicer 가 같은 dataSourceId (또는 inline rows) 를 가리켜야 의미 있음.
    """
    meta: BlockMeta | None = None


class Source2(BaseModel):
    """
    Inline source — distinct values 직접 명시. 작은 enum 에 유용.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['inline']
    rows: list[dict[str, str | float | None]]


class Source3(BaseModel):
    """
    Same DataSourceBlock 의 rows 를 slicer 데이터로 사용. 보통 같은 Pivot 이 가리키는 DataSourceBlock 과 같은 id 를 적는다.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['data-source']
    data_source_id: Ulid = Field(..., alias='dataSourceId')


class SlicerBlock(BaseModel):
    """
    Slicer widget — cross-widget visual filter. 같은 source 의 한 field 의 distinct values 를 chip group 으로 노출. 사용자가 chip 을 토글하면 zustand store (`slicerStore`) 의 active set 이 변경되고, boundSlicers 로 이 slicer 를 listen 하는 모든 widget (현 구현: Pivot) 이 filter 를 재적용해 다시 렌더. multiSelect=false (default) 면 한 번에 하나만, true 면 다중 선택.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['slicer']
    id: Ulid
    label: str | None = None
    """
    chip group 위 라벨 (e.g. '부서')
    """
    field: str = Field(..., min_length=1)
    """
    어느 field 를 slice 할지 (e.g. 'dept')
    """
    source: Source2 | Source3 | None = None
    multi_select: bool | None = Field(False, alias='multiSelect')
    """
    true 면 다중 chip 활성 가능 (Ctrl+클릭). false 면 한 번에 하나
    """
    default: list[str] | None = None
    """
    최초 활성 값. 미명시 시 빈 set (모든 값 통과)
    """
    meta: BlockMeta | None = None


class Source4(BaseModel):
    """
    Inline source — 날짜 도메인을 rows 의 `field` 값에서 추론. SlicerBlock 과 동일 shape.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['inline']
    rows: list[dict[str, str | float | None]]


class Source5(BaseModel):
    """
    Same DataSourceBlock 의 rows 를 timeline 데이터로 사용.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['data-source']
    data_source_id: Ulid = Field(..., alias='dataSourceId')


class TimelineBlock(BaseModel):
    """
    Timeline widget — date-range cross-widget filter (G4). 사용자가 from/to 두 슬라이더로 [min, max] 부분구간을 선택하면 zustand store (`slicerStore`) 의 active set 에 `[isoFrom, isoTo]` 2-원소 배열로 기록되고, boundSlicers 로 이 timeline 을 listen 하는 모든 widget 이 filter (`{field, op:'between', value: [isoFrom, isoTo]}`) 로 받는다. SlicerBlock 과 같은 store / 같은 boundSlicers 메커니즘을 공유하므로 viewer 의 한 픽커로 둘 다 binding 가능. min/max 는 inline rows 의 `block.field` distinct 값 또는 schema 의 explicit `min`/`max` 로 결정 (둘 다 ISO 날짜 문자열).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['timeline']
    id: Ulid
    label: str | None = None
    """
    슬라이더 위 라벨 (e.g. '기간')
    """
    field: str = Field(..., min_length=1)
    """
    필터링할 날짜 field 이름 (e.g. 'date'). 값은 ISO-8601 (YYYY-MM-DD) 가정.
    """
    source: Source4 | Source5 | None = None
    min: str | None = None
    """
    도메인 최소값 (ISO date). 명시하지 않으면 rows[field] 의 min.
    """
    max: str | None = None
    """
    도메인 최대값 (ISO date). 명시하지 않으면 rows[field] 의 max.
    """
    default: list[str] | None = Field(None, max_length=2, min_length=2)
    """
    [isoFrom, isoTo] — 최초 활성 구간. 미명시 시 빈 set (전체 통과)
    """
    meta: BlockMeta | None = None


class Render(Enum):
    table = 'table'
    chart = 'chart'
    kpi_cards = 'kpi-cards'


class ChartType1(Enum):
    line = 'line'
    bar = 'bar'
    pie = 'pie'
    area = 'area'
    radar = 'radar'
    scatter = 'scatter'
    xy_line = 'xy-line'
    boxplot = 'boxplot'


class Engine2(Enum):
    recharts = 'recharts'
    echarts = 'echarts'


class Interactions1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    key_points: list[KeyPoint] | None = Field(None, alias='keyPoints')
    regions: list[Region] | None = None


class ChartOptions(BaseModel):
    """
    Per-document chart styling overrides (only for render=chart). Deep-merged ON TOP of widget-provided defaults — set just the fields you want to change.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    chart_type: ChartType1 | None = Field(None, alias='chartType')
    engine: Engine2 | None = None
    title: str | None = None
    interactions: Interactions1 | None = None
    options: dict[str, Any] | None = None
    """
    Raw ECharts EChartsOption fragment, deep-merged after widget defaults + interactions.
    """


class DataSourceBlock(BaseModel):
    """
    Live data block. Widget response shapes the data; render type fixes the renderer. For render=chart, the widget may include chartType / engine / interactions / options inline; chartOptions on the block deep-merges on top so document authors can override per-doc styling without touching the widget.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['data-source']
    id: Ulid
    endpoint: str = Field(..., pattern='^/api/v1/widgets/')
    params: dict[str, Any] | None = None
    render: Render
    refresh_interval: int | None = Field(None, alias='refreshInterval', ge=30, le=3600)
    chart_options: ChartOptions | None = Field(None, alias='chartOptions')
    """
    Per-document chart styling overrides (only for render=chart). Deep-merged ON TOP of widget-provided defaults — set just the fields you want to change.
    """
    meta: BlockMeta | None = None


class Provider1(Enum):
    grafana = 'grafana'
    tableau = 'tableau'
    superset = 'superset'


class DashboardEmbedBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['dashboard-embed']
    id: Ulid
    provider: Provider1
    panel_id: str = Field(..., alias='panelId')
    params: dict[str, Any] | None = None
    meta: BlockMeta | None = None


class Kind3(Enum):
    number = 'number'
    text = 'text'
    select = 'select'


class Input(BaseModel):
    name: str
    label: str
    default: str | float | bool | None = None
    kind: Kind3 | None = Kind3.number


class CalculatorBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['calculator']
    id: Ulid
    inputs: list[Input]
    formula: str
    """
    안전한 표현식 (mathjs 등)
    """
    label: str | None = None
    meta: BlockMeta | None = None


class Viewbox(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    w: int = Field(..., ge=100, le=4000)
    h: int = Field(..., ge=100, le=4000)


class Point1(RootModel[list[float]]):
    root: list[float] = Field(..., max_length=2, min_length=2)


class WhiteboardElement1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['stroke']
    id: str
    points: list[Point1]
    stroke: str
    stroke_width: float = Field(..., alias='strokeWidth', ge=1.0, le=32.0)


class Shape(Enum):
    rect = 'rect'
    ellipse = 'ellipse'
    line = 'line'
    arrow = 'arrow'


class WhiteboardElement2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['shape']
    id: str
    shape: Shape
    x: float
    y: float
    w: float
    h: float
    stroke: str
    stroke_width: float = Field(..., alias='strokeWidth', ge=1.0, le=32.0)
    fill: str | None = None


class WhiteboardElement3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['text']
    id: str
    x: float
    y: float
    text: str
    font_size: float = Field(..., alias='fontSize', ge=8.0, le=96.0)
    color: str


class WhiteboardElement(
    RootModel[WhiteboardElement1 | WhiteboardElement2 | WhiteboardElement3]
):
    root: WhiteboardElement1 | WhiteboardElement2 | WhiteboardElement3


class Kind4(Enum):
    text = 'text'
    long_text = 'long-text'
    email = 'email'
    number = 'number'
    select = 'select'
    multi_select = 'multi-select'
    checkbox = 'checkbox'
    rating_5 = 'rating-5'
    date = 'date'


class FormQuestion(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    kind: Kind4
    label: str
    required: bool | None = False
    placeholder: str | None = None
    options: list[str] | None = None
    min: float | None = None
    """
    Numeric kinds (number): minimum allowed value (inclusive).
    """
    max: float | None = None
    """
    Numeric kinds (number): maximum allowed value (inclusive).
    """
    min_length: int | None = Field(None, alias='minLength', ge=0)
    """
    Text kinds (text/long-text/email): minimum string length.
    """
    max_length: int | None = Field(None, alias='maxLength', ge=0)
    """
    Text kinds (text/long-text/email): maximum string length.
    """
    pattern: str | None = None
    """
    Text kinds: ECMA-262 RegExp source. BE compiles defensively (silent skip on invalid).
    """


class Kind5(Enum):
    single_choice = 'single-choice'
    multi_choice = 'multi-choice'
    true_false = 'true-false'
    short_text = 'short-text'


class QuizQuestion(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    kind: Kind5
    label: str
    options: list[str] | None = None
    correct: str | list[str] | bool
    explanation: str | None = None
    points: int | None = Field(1, ge=0)


class From(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    x: float
    y: float


class To(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    x: float
    y: float


class AnnotationElement1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['arrow']
    id: str
    from_: From = Field(..., alias='from')
    to: To
    color: str
    label: str | None = None


class AnnotationElement2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['rect']
    id: str
    x: float
    y: float
    w: float
    h: float
    color: str
    label: str | None = None


class Anchor(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    x: float
    y: float


class AnnotationElement3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['callout']
    id: str
    x: float
    y: float
    anchor: Anchor | None = None
    label: str
    """
    Annotation label (was `text` pre-pass-2). BE normaliser rewrites legacy `text` → `label` on read.
    """
    color: str
    bg_color: str | None = Field(None, alias='bgColor')
    """
    Optional callout label background colour. Default is white (hardcoded for readability on top of user images — see svg-block-audit cycle). Set to override (e.g. when the underlying image is uniformly bright and white blends in).
    """


class AnnotationElement4(BaseModel):
    """
    이미지 위 자유 위치 multi-line 텍스트 박스. callout(짧은 라벨) 과 달리 박스 크기 (w, h) 와 줄바꿈을 가진 본문성 주석. 이미지의 특정 영역을 설명하는 글을 직접 얹는 용도.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['textbox']
    id: str
    x: float
    y: float
    w: float
    h: float
    text: str
    """
    Multi-line plain text. \\n 으로 줄 구분.
    """
    color: str
    """
    텍스트 색.
    """
    font_size: float | None = Field(None, alias='fontSize')
    """
    정규화 좌표계 기준 글자 크기 (기본 0.025). 좌표가 0-1 이라 일반적으로 0.015~0.06.
    """
    bg: str | None = None
    """
    박스 배경색 (선택). 미지정 시 반투명 흰색 폴백.
    """


class AnnotationElement(
    RootModel[
        AnnotationElement1
        | AnnotationElement2
        | AnnotationElement3
        | AnnotationElement4
    ]
):
    root: (
        AnnotationElement1
        | AnnotationElement2
        | AnnotationElement3
        | AnnotationElement4
    )


class Options6(BaseModel):
    """
    Visual rendering options. All fields optional with sensible defaults.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    stripe: bool | None = None
    """
    Zebra-striped data rows for readability. Default true; set false to disable. Header row is unaffected.
    """


class SpreadsheetBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['spreadsheet']
    id: Ulid
    title: str | None = None
    cols: int = Field(6, ge=1, le=26)
    rows: int = Field(10, ge=1, le=200)
    headers: list[str] | None = None
    cells: dict[str, str]
    """
    Sparse map of cell-ref → raw cell input (e.g. {'A1':'42', 'B2':'=SUM(A1:A10)'})
    """
    options: Options6 | None = None
    """
    Visual rendering options. All fields optional with sensible defaults.
    """
    meta: BlockMeta | None = None


class Style2(Enum):
    """
    Citation style label (numeric / alphabetic / author-year). Currently informational — the FE renders ordered list either way.
    """

    numeric = 'numeric'
    alphabetic = 'alphabetic'
    author_year = 'author-year'


class Entry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    key: str | None = Field(None, max_length=60, pattern='^[A-Za-z0-9_-]+$')
    """
    Optional citation key used by [[cite:KEY]] inline references. Alphanumeric / hyphen / underscore.
    """
    text: str = Field(..., max_length=2000, min_length=1)
    """
    Formatted reference body — e.g. 'Smith, J. (2020). Foo bar. Journal of X, 3(2), 14-22.'
    """
    url: str | None = Field(None, max_length=1000)
    """
    Optional canonical URL (DOI, journal page).
    """


class Options7(BaseModel):
    """
    표시 옵션. 모두 optional, default 동작은 ON.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    stripe: bool | None = True
    """
    참고문헌 항목 단위 zebra-striping (각 entry 행).
    """


class BibliographyBlock(BaseModel):
    """
    Reference list (참고문헌). Citations elsewhere in the document use the [[cite:KEY]] inline syntax to anchor-link into entries here. Most often produced by the DOCX importer when it sees a 'References' / '참고문헌' / 'Bibliography' heading.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['bibliography']
    id: Ulid
    title: str | None = Field(None, max_length=200)
    """
    Optional override for the block heading. Defaults to '참고문헌' in the FE renderer.
    """
    style: Style2 | None = None
    """
    Citation style label (numeric / alphabetic / author-year). Currently informational — the FE renders ordered list either way.
    """
    entries: list[Entry] = Field(..., min_length=1)
    options: Options7 | None = None
    """
    표시 옵션. 모두 optional, default 동작은 ON.
    """
    meta: BlockMeta | None = None


class RelatedDoc(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    slug: Slug
    relation: str = Field(..., examples=['참고', '선행', '후속', '유사'])


class GlossaryItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    term: str = Field(..., min_length=1)
    definition: str = Field(..., min_length=1)


class Type(Enum):
    internal = 'internal'
    external = 'external'


class Reference(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Type
    label: str
    url: AnyUrl | None = None


class Infobox(RootModel[dict[str, str | list[str] | InfoboxRich | list[InfoboxRich]]]):
    """
    우상단 정보 박스. 키=라벨, 값=문자열, 문자열 배열, 또는 풍부한 표현(링크/뱃지/아이콘)을 위한 InfoboxRich 객체. 기존 문자열 형태는 그대로 호환.
    """

    root: dict[str, str | list[str] | InfoboxRich | list[InfoboxRich]]


class CellBlock(RootModel[ParagraphBlock | ImageBlock | ListBlock]):
    root: ParagraphBlock | ImageBlock | ListBlock
    """
    Block subset allowed inside a TableBlock cell's `blocks` array. Intentionally narrow to keep table cell rendering tractable — only paragraph/image/list.
    """


class Cell(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    r: int = Field(..., ge=0)
    c: int = Field(..., ge=0)
    row_span: int | None = Field(None, alias='rowSpan', ge=1)
    col_span: int | None = Field(None, alias='colSpan', ge=1)
    text: str | None = None
    blocks: list[CellBlock] | None = Field(None, min_length=1)
    """
    Mixed-content cell payload. When present, renderers ignore `text` and lay out these blocks inside the cell. Restricted to paragraph/image/list to keep cell layout tractable — tables-in-tables and callouts-in-cells are intentionally out of scope.
    """
    header: bool | None = None
    """
    True for header-row cells (rendered as <th>).
    """
    align: Align1 | None = None
    """
    Per-cell horizontal alignment override (wins over column default).
    """
    bg: str | None = Field(None, pattern='^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')
    """
    Cell background color (CSS hex).
    """
    bold: bool | None = None
    """
    Bold text in this cell.
    """
    color: str | None = Field(None, pattern='^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')
    """
    Cell text color (CSS hex).
    """


class TableBlock(BaseModel):
    """
    Table block. Two layout modes: flat (`headers` + `rows`, the common case) and sparse (`cells`, used whenever cells are merged or styled per-cell). The renderer prefers `cells` when present. Optional `columns` carries per-column metadata (width / align / dtype / format) that applies to BOTH modes — column index is well-defined in either layout.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['table']
    id: Ulid
    caption: str | None = Field(None, max_length=500)
    """
    Optional caption rendered below the table; participates in auto-numbering ('표 N: ...').
    """
    headers: list[str]
    rows: list[list[str]]
    cells: list[Cell] | None = None
    """
    Optional sparse cell list for tables with merged or styled cells (DOCX gridSpan/vMerge round-trip + per-cell style overrides). When present, the renderer ignores headers/rows and lays out from this list. Each cell occupies (r..r+rowSpan-1) × (c..c+colSpan-1); covered slots have no entry. r/c are 0-indexed; the first row of a header-mode table is the header row. A cell carries content via either `text` (plain string, the common case) or `blocks` (mixed content — paragraph/image/list). Exactly one of the two MUST be set; empty cell ⇒ text=''.
    """
    columns: list[Column] | None = None
    """
    Optional per-column metadata. Index matches column index in both flat and sparse layouts. Missing entries fall back to defaults (left-align, text dtype, auto width).
    """
    footer: Footer | None = None
    """
    Optional footer row showing per-column aggregates. Computed at render time from `rows` (flat mode) — sparse mode is skipped because merged-cell semantics make column-wise sums ambiguous.
    """
    options: Options1 | None = None
    bound_slicers: list[Ulid] | None = Field(None, alias='boundSlicers')
    """
    ULIDs of SlicerBlocks whose active value sets should filter this table. Each slicer's `field` must match one of the table's `headers` (1:1 column-by-header mapping); columns whose header doesn't match any active slicer pass through unchanged. Empty/missing → no slicer-driven filter, equivalent to slicer 'All' state. Sparse `cells` layout: filter is skipped (merged-cell semantics make row-by-row filtering ambiguous).
    """
    meta: BlockMeta | None = None


class OrgChartBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['org-chart']
    id: Ulid
    root: OrgChartNode
    layout: Layout1 | None = Layout1.tree
    meta: BlockMeta | None = None


class WhiteboardBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['whiteboard']
    id: Ulid
    title: str | None = None
    viewbox: Viewbox
    elements: list[WhiteboardElement]
    meta: BlockMeta | None = None


class FormBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['form']
    id: Ulid
    title: str | None = None
    description: str | None = None
    questions: list[FormQuestion] = Field(..., min_length=1)
    submit_label: str | None = '제출'
    thanks_message: str | None = '응답해 주셔서 감사합니다.'
    allow_multiple_responses: bool | None = False
    meta: BlockMeta | None = None


class QuizBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['quiz']
    id: Ulid
    title: str | None = None
    description: str | None = None
    questions: list[QuizQuestion] = Field(..., min_length=1)
    passing_score: int | None = Field(70, ge=0, le=100)
    shuffle: bool | None = False
    max_attempts: int | None = Field(0, ge=0)
    show_answers_after: bool | None = True
    meta: BlockMeta | None = None


class ImageAnnotationBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['image-annotation']
    id: Ulid
    image_id: str = Field(..., alias='imageId')
    """
    FK to images table (mxwp-images). Camel-case to match ImageBlock; BE normalizes legacy 'image_id' on read.
    """
    caption: str | None = None
    annotations: list[AnnotationElement]
    meta: BlockMeta | None = None


class DocumentjsonV10(BaseModel):
    """
    MX White Paper 단일 진실 공급원(SSOT). Section 트리(level 1~3) + Block 배열 본문. PROJECT_PLAN.md / Plan / Design / Do 문서의 모든 데이터 모델 참조처.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: Literal['1.0']
    id: Ulid
    slug: Slug
    title: str = Field(..., max_length=200, min_length=1)
    summary: str | None = Field(None, max_length=500)
    metadata: DocumentMeta
    infobox: Infobox | None = None
    sections: list[Section]
    """
    최상위 섹션은 반드시 level=1 (BE 가 검증). 자식 섹션은 부모 level+1.
    """
    related_documents: list[RelatedDoc] | None = Field([], validate_default=True)
    glossary: list[GlossaryItem] | None = Field([], validate_default=True)
    references: list[Reference] | None = Field([], validate_default=True)
    see_also: list[Slug] | None = Field([], validate_default=True)
    variables: dict[str, str] | None = None
    """
    Map of variable names → fill-in strings used to substitute {{var}} tokens at render time.
    """
    custom_css: str | None = Field(None, max_length=10000)
    """
    Optional CSS injected into the doc's render. Sandboxed: no <script>, no expression(), no url(javascript:), no @import, no behavior:.
    """


class Section(BaseModel):
    """
    Document outline node. Recursive — `subsections` is another Section[]. Top-level entries MUST have level=1; child level = parent.level + 1 (enforced by the BE renumber/validate pass). The visual rendering caps at HTML <h6> (level 5+ all render as h6) but schema-wise depth is unbounded.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: Ulid
    number: str | None = Field(None, pattern='^\\d+(?:\\.\\d+)*$')
    """
    1.2.3.4… dotted ordinal recomputed by the BE on every save.
    """
    level: int = Field(..., ge=1)
    """
    1-based depth. BE rejects values that don't match the tree position.
    """
    title: str = Field(..., max_length=200, min_length=1)
    layout: Layout | None = None
    """
    Visual layout for this section's blocks. Drives both the wiki view (block arrangement inside the section) and presentation view (slide template). Defaults to 'stack' (existing behaviour: blocks render top-to-bottom). 'two-col' splits blocks alternately into two columns. 'image-left'/'image-right' put the first ImageBlock on one side and remaining blocks on the other. 'title-only' renders just the section heading (PPT cover style). 'full-bleed' uses the first ImageBlock as a full-width background with subsequent blocks overlaid.
    """
    layout_widths: list[LayoutWidth] | None = Field(
        None, alias='layoutWidths', max_length=2, min_length=2
    )
    """
    Per-pane percentage widths for two-pane layouts (two-col / image-left / image-right). Length MUST equal 2 when present, each value 10..90, sum SHOULD equal 100 (FE normalises). Ignored for stack / title-only / full-bleed. Omit for equal 50/50 split.
    """
    blocks: list[Block]
    subsections: list[Section] | None = Field([], validate_default=True)


class ColumnsBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['columns']
    id: Ulid
    columns: list[list[Block]] = Field(..., max_length=4, min_length=2)
    widths: list[Width1] | None = Field(None, max_length=4, min_length=2)
    """
    Optional per-column widths as percentages of the row. Length MUST equal columns.length when present, each value 5..95, and the sum SHOULD equal 100 (server normalises). Omit for equal split.
    """
    meta: BlockMeta | None = None


class Tab(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    label: str
    blocks: list[Block]


class TabsBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['tabs']
    id: Ulid
    tabs: list[Tab] = Field(..., min_length=1)
    meta: BlockMeta | None = None


class Item2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    label: str
    blocks: list[Block]


class AccordionBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['accordion']
    id: Ulid
    items: list[Item2] = Field(..., min_length=1)
    meta: BlockMeta | None = None


class Block(
    RootModel[
        Annotated[
        ParagraphBlock
        | Heading4Block
        | ListBlock
        | QuoteBlock
        | CalloutBlock
        | CodeBlock
        | MathBlock
        | TableBlock
        | KpiCardsBlock
        | ChartBlock
        | GanttBlock
        | FlowBlock
        | OrgChartBlock
        | IframeBlock
        | VideoBlock
        | ImageBlock
        | GalleryBlock
        | FileBlock
        | DocLinkCardBlock
        | GlossaryRefBlock
        | ColumnsBlock
        | TabsBlock
        | AccordionBlock
        | DataSourceBlock
        | DashboardEmbedBlock
        | CalculatorBlock
        | WhiteboardBlock
        | FormBlock
        | PdfBlock
        | QuizBlock
        | ImageAnnotationBlock
        | SpreadsheetBlock
        | BibliographyBlock
        | SpacerBlock
        | FigureIndexBlock
        | PivotTableBlock
        | SlicerBlock
        | TimelineBlock
        ,
        Field(discriminator='type'),
    ]
    ]
):
    root: (
        ParagraphBlock
        | Heading4Block
        | ListBlock
        | QuoteBlock
        | CalloutBlock
        | CodeBlock
        | MathBlock
        | TableBlock
        | KpiCardsBlock
        | ChartBlock
        | GanttBlock
        | FlowBlock
        | OrgChartBlock
        | IframeBlock
        | VideoBlock
        | ImageBlock
        | GalleryBlock
        | FileBlock
        | DocLinkCardBlock
        | GlossaryRefBlock
        | ColumnsBlock
        | TabsBlock
        | AccordionBlock
        | DataSourceBlock
        | DashboardEmbedBlock
        | CalculatorBlock
        | WhiteboardBlock
        | FormBlock
        | PdfBlock
        | QuizBlock
        | ImageAnnotationBlock
        | SpreadsheetBlock
        | BibliographyBlock
        | SpacerBlock
        | FigureIndexBlock
        | PivotTableBlock
        | SlicerBlock
        | TimelineBlock
    )


OrgChartNode.model_rebuild()
DocumentjsonV10.model_rebuild()
Section.model_rebuild()
ColumnsBlock.model_rebuild()
Tab.model_rebuild()
Item2.model_rebuild()
