# generated by datamodel-codegen:
#   filename:  document.json

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import AnyUrl, BaseModel, ConfigDict, Field, RootModel


class Ulid(RootModel[str]):
    root: str = Field(..., pattern='^[0-9A-HJKMNP-TV-Z]{26}$')
    """
    Crockford base32 ULID
    """


class Slug(RootModel[str]):
    root: str = Field(
        ..., pattern='^[a-z0-9\\uAC00-\\uD7A3][a-z0-9\\uAC00-\\uD7A3-]{0,99}$'
    )
    """
    url-safe identifier (lowercase ASCII, digits, hyphen, Hangul)
    """


class Confidentiality(Enum):
    public = 'public'
    internal = 'internal'
    restricted = 'restricted'


class DocumentMeta(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    division: str = Field(..., min_length=1)
    team: str | None = None
    group: str | None = None
    part: str | None = None
    owners: list[str] = Field(..., min_length=1)
    reviewers: list[str] | None = []
    tags: list[str] | None = []
    category: str | None = None
    confidentiality: Confidentiality


class Infobox(RootModel[dict[str, str | list[str]]]):
    """
    우상단 정보 박스. 키=라벨, 값=문자열 또는 문자열 배열
    """

    root: dict[str, str | list[str]]


class Align(Enum):
    left = 'left'
    center = 'center'
    right = 'right'
    full = 'full'


class Permission(Enum):
    all = 'all'
    editor = 'editor'
    admin = 'admin'


class Level(Enum):
    """
    Heading 블록(heading-4 type)에서 실제 보여줄 단계. 2=큰 제목, 3=중간 제목, 4=작은 제목(기본). 다른 블록 타입에서는 무시됨.
    """

    int_2 = 2
    int_3 = 3
    int_4 = 4


class BlockMeta(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    align: Align | None = None
    collapsed: bool | None = None
    locked: bool | None = None
    permission: Permission | None = None
    note: str | None = None
    level: Level | None = None
    """
    Heading 블록(heading-4 type)에서 실제 보여줄 단계. 2=큰 제목, 3=중간 제목, 4=작은 제목(기본). 다른 블록 타입에서는 무시됨.
    """
    width: int | None = Field(None, ge=32, le=4000)
    """
    사용자 지정 블록 너비(px). 미지정 또는 0이면 부모 컨테이너에 맞춤(기존 동작).
    """
    height: int | None = Field(None, ge=32, le=4000)
    """
    사용자 지정 블록 높이(px). 미지정이면 콘텐츠 자동 높이(기존 동작).
    """


class ParagraphBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['paragraph']
    id: Ulid
    text: str
    meta: BlockMeta | None = None


class Heading4Block(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['heading-4']
    id: Ulid
    title: str = Field(..., max_length=200, min_length=1)
    meta: BlockMeta | None = None


class Style(Enum):
    bullet = 'bullet'
    number = 'number'
    check = 'check'


class ListBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['list']
    id: Ulid
    style: Style
    items: list[str]
    meta: BlockMeta | None = None


class QuoteBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['quote']
    id: Ulid
    text: str
    cite: str | None = None
    meta: BlockMeta | None = None


class Variant(Enum):
    info = 'info'
    warn = 'warn'
    danger = 'danger'
    tip = 'tip'


class CalloutBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['callout']
    id: Ulid
    variant: Variant
    title: str | None = None
    text: str
    meta: BlockMeta | None = None


class CodeBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['code']
    id: Ulid
    language: str
    code: str
    filename: str | None = None
    meta: BlockMeta | None = None


class Display(Enum):
    block = 'block'
    inline = 'inline'


class MathBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['math']
    id: Ulid
    expression: str
    """
    LaTeX (KaTeX 호환)
    """
    display: Display | None = 'block'
    meta: BlockMeta | None = None


class Options(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    sortable: bool | None = None
    searchable: bool | None = None


class TableBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['table']
    id: Ulid
    headers: list[str]
    rows: list[list[str]]
    options: Options | None = None
    meta: BlockMeta | None = None


class Trend(Enum):
    up = 'up'
    down = 'down'
    flat = 'flat'


class Item(BaseModel):
    label: str
    value: str | float
    delta: str | float | None = None
    trend: Trend | None = None


class KpiCardsBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['kpi-cards']
    id: Ulid
    items: list[Item]
    meta: BlockMeta | None = None


class ChartType(Enum):
    line = 'line'
    bar = 'bar'
    pie = 'pie'
    area = 'area'
    radar = 'radar'
    scatter = 'scatter'


class Series(BaseModel):
    name: str
    values: list[float]


class Data(BaseModel):
    labels: list[str]
    series: list[Series]


class ChartBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['chart']
    id: Ulid
    chart_type: ChartType = Field(..., alias='chartType')
    title: str | None = None
    data: Data
    options: dict[str, Any] | None = None
    meta: BlockMeta | None = None


class Task(BaseModel):
    name: str
    start: str
    end: str
    progress: float | None = Field(None, ge=0.0, le=100.0)


class GanttBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['gantt']
    id: Ulid
    tasks: list[Task]
    meta: BlockMeta | None = None


class Engine(Enum):
    mermaid = 'mermaid'
    excalidraw = 'excalidraw'


class FlowBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['flow']
    id: Ulid
    engine: Engine
    source: str
    """
    Mermaid DSL 또는 excalidraw JSON
    """
    meta: BlockMeta | None = None


class Layout(Enum):
    tree = 'tree'
    horizontal = 'horizontal'


class OrgChartNode(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    label: str
    role: str | None = None
    children: list[OrgChartNode] | None = Field([], validate_default=True)


class IframeBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['iframe']
    id: Ulid
    src: AnyUrl
    """
    사내 화이트리스트 도메인만
    """
    title: str | None = None
    height: int | None = Field(None, ge=100, le=2000)
    meta: BlockMeta | None = None


class Provider(Enum):
    intra = 'intra'
    youtube = 'youtube'
    vimeo = 'vimeo'


class VideoBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['video']
    id: Ulid
    url: AnyUrl
    title: str | None = None
    provider: Provider | None = 'intra'
    meta: BlockMeta | None = None


class Width(Enum):
    sm = 'sm'
    md = 'md'
    lg = 'lg'
    full = 'full'


class ImageBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['image']
    id: Ulid
    image_id: Ulid = Field(..., alias='imageId')
    """
    FK to images table
    """
    caption: str | None = Field(None, max_length=500)
    alt: str | None = Field(None, max_length=200)
    width: Width | None = 'md'
    link: str | None = None
    """
    외부 URL 또는 위키 slug
    """
    meta: BlockMeta | None = None


class Layout1(Enum):
    grid = 'grid'
    carousel = 'carousel'


class Item1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    image_id: Ulid = Field(..., alias='imageId')
    caption: str | None = Field(None, max_length=500)
    alt: str | None = Field(None, max_length=200)


class GalleryBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['gallery']
    id: Ulid
    layout: Layout1 | None = 'grid'
    items: list[Item1] = Field(..., min_length=1)
    meta: BlockMeta | None = None


class FileBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['file']
    id: Ulid
    file_id: Ulid = Field(..., alias='fileId')
    name: str
    size: int | None = Field(None, ge=0)
    mime: str | None = None
    meta: BlockMeta | None = None


class DocLinkCardBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['doc-link-card']
    id: Ulid
    slug: Slug
    show_summary: bool | None = Field(True, alias='showSummary')
    meta: BlockMeta | None = None


class GlossaryRefBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['glossary-ref']
    id: Ulid
    term: str
    meta: BlockMeta | None = None


class Render(Enum):
    table = 'table'
    chart = 'chart'
    kpi_cards = 'kpi-cards'


class DataSourceBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['data-source']
    id: Ulid
    endpoint: str = Field(..., pattern='^/api/v1/widgets/')
    params: dict[str, Any] | None = None
    render: Render
    refresh_interval: int | None = Field(None, alias='refreshInterval', ge=30, le=3600)
    meta: BlockMeta | None = None


class Provider1(Enum):
    grafana = 'grafana'
    tableau = 'tableau'
    superset = 'superset'


class DashboardEmbedBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['dashboard-embed']
    id: Ulid
    provider: Provider1
    panel_id: str = Field(..., alias='panelId')
    params: dict[str, Any] | None = None
    meta: BlockMeta | None = None


class Kind(Enum):
    number = 'number'
    text = 'text'
    select = 'select'


class Input(BaseModel):
    name: str
    label: str
    default: str | float | bool | None = None
    kind: Kind | None = 'number'


class CalculatorBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['calculator']
    id: Ulid
    inputs: list[Input]
    formula: str
    """
    안전한 표현식 (mathjs 등)
    """
    label: str | None = None
    meta: BlockMeta | None = None


class Viewbox(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    w: int = Field(..., ge=100, le=4000)
    h: int = Field(..., ge=100, le=4000)


class Point(RootModel[list[float]]):
    root: list[float] = Field(..., max_length=2, min_length=2)


class WhiteboardElement1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['stroke']
    id: str
    points: list[Point]
    stroke: str
    stroke_width: float = Field(..., alias='strokeWidth', ge=1.0, le=32.0)


class Shape(Enum):
    rect = 'rect'
    ellipse = 'ellipse'
    line = 'line'
    arrow = 'arrow'


class WhiteboardElement2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['shape']
    id: str
    shape: Shape
    x: float
    y: float
    w: float
    h: float
    stroke: str
    stroke_width: float = Field(..., alias='strokeWidth', ge=1.0, le=32.0)
    fill: str | None = None


class WhiteboardElement3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['text']
    id: str
    x: float
    y: float
    text: str
    font_size: float = Field(..., alias='fontSize', ge=8.0, le=96.0)
    color: str


class WhiteboardElement(
    RootModel[WhiteboardElement1 | WhiteboardElement2 | WhiteboardElement3]
):
    root: WhiteboardElement1 | WhiteboardElement2 | WhiteboardElement3


class Kind1(Enum):
    text = 'text'
    long_text = 'long-text'
    email = 'email'
    number = 'number'
    select = 'select'
    multi_select = 'multi-select'
    checkbox = 'checkbox'
    rating_5 = 'rating-5'
    date = 'date'


class FormQuestion(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    kind: Kind1
    label: str
    required: bool | None = False
    placeholder: str | None = None
    options: list[str] | None = None


class RelatedDoc(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    slug: Slug
    relation: str = Field(..., examples=['참고', '선행', '후속', '유사'])


class GlossaryItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    term: str = Field(..., min_length=1)
    definition: str = Field(..., min_length=1)


class Type(Enum):
    internal = 'internal'
    external = 'external'


class Reference(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Type
    label: str
    url: AnyUrl | None = None


class OrgChartBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['org-chart']
    id: Ulid
    root: OrgChartNode
    layout: Layout | None = 'tree'
    meta: BlockMeta | None = None


class WhiteboardBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['whiteboard']
    id: Ulid
    title: str | None = None
    viewbox: Viewbox
    elements: list[WhiteboardElement]
    meta: BlockMeta | None = None


class FormBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['form']
    id: Ulid
    title: str | None = None
    description: str | None = None
    questions: list[FormQuestion] = Field(..., min_length=1)
    submit_label: str | None = '제출'
    thanks_message: str | None = '응답해 주셔서 감사합니다.'
    allow_multiple_responses: bool | None = False
    meta: BlockMeta | None = None


class DocumentjsonV10(BaseModel):
    """
    MX White Paper 단일 진실 공급원(SSOT). Section 트리(level 1~3) + Block 배열 본문. PROJECT_PLAN.md / Plan / Design / Do 문서의 모든 데이터 모델 참조처.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: Literal['1.0']
    id: Ulid
    slug: Slug
    title: str = Field(..., max_length=200, min_length=1)
    summary: str | None = Field(None, max_length=500)
    metadata: DocumentMeta
    infobox: Infobox | None = None
    sections: list[SectionLevel1]
    """
    최상위 섹션은 반드시 level=1
    """
    related_documents: list[RelatedDoc] | None = Field([], validate_default=True)
    glossary: list[GlossaryItem] | None = Field([], validate_default=True)
    references: list[Reference] | None = Field([], validate_default=True)
    see_also: list[Slug] | None = Field([], validate_default=True)
    variables: dict[str, str] | None = None
    """
    Map of variable names → fill-in strings used to substitute {{var}} tokens at render time.
    """


class SectionLevel1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Ulid
    number: str | None = Field(None, pattern='^\\d+$')
    level: Literal[1]
    title: str = Field(..., max_length=200, min_length=1)
    blocks: list[Block]
    subsections: list[SectionLevel2]


class SectionLevel2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Ulid
    number: str | None = Field(None, pattern='^\\d+\\.\\d+$')
    level: Literal[2]
    title: str = Field(..., max_length=200, min_length=1)
    blocks: list[Block]
    subsections: list[SectionLevel3]


class SectionLevel3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Ulid
    number: str | None = Field(None, pattern='^\\d+\\.\\d+\\.\\d+$')
    level: Literal[3]
    title: str = Field(..., max_length=200, min_length=1)
    blocks: list[Block]
    subsections: list[Any] | None = Field([], max_length=0)
    """
    level 3은 더 깊은 섹션 불가 (heading-4 Block으로 표현)
    """


class ColumnsBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['columns']
    id: Ulid
    columns: list[list[Block]] = Field(..., max_length=4, min_length=2)
    meta: BlockMeta | None = None


class Tab(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    label: str
    blocks: list[Block]


class TabsBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['tabs']
    id: Ulid
    tabs: list[Tab] = Field(..., min_length=1)
    meta: BlockMeta | None = None


class Item2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    label: str
    blocks: list[Block]


class AccordionBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['accordion']
    id: Ulid
    items: list[Item2] = Field(..., min_length=1)
    meta: BlockMeta | None = None


class Block(
    RootModel[
        ParagraphBlock
        | Heading4Block
        | ListBlock
        | QuoteBlock
        | CalloutBlock
        | CodeBlock
        | MathBlock
        | TableBlock
        | KpiCardsBlock
        | ChartBlock
        | GanttBlock
        | FlowBlock
        | OrgChartBlock
        | IframeBlock
        | VideoBlock
        | ImageBlock
        | GalleryBlock
        | FileBlock
        | DocLinkCardBlock
        | GlossaryRefBlock
        | ColumnsBlock
        | TabsBlock
        | AccordionBlock
        | DataSourceBlock
        | DashboardEmbedBlock
        | CalculatorBlock
        | WhiteboardBlock
        | FormBlock
    ]
):
    root: (
        ParagraphBlock
        | Heading4Block
        | ListBlock
        | QuoteBlock
        | CalloutBlock
        | CodeBlock
        | MathBlock
        | TableBlock
        | KpiCardsBlock
        | ChartBlock
        | GanttBlock
        | FlowBlock
        | OrgChartBlock
        | IframeBlock
        | VideoBlock
        | ImageBlock
        | GalleryBlock
        | FileBlock
        | DocLinkCardBlock
        | GlossaryRefBlock
        | ColumnsBlock
        | TabsBlock
        | AccordionBlock
        | DataSourceBlock
        | DashboardEmbedBlock
        | CalculatorBlock
        | WhiteboardBlock
        | FormBlock
    )


OrgChartNode.model_rebuild()
DocumentjsonV10.model_rebuild()
SectionLevel1.model_rebuild()
SectionLevel2.model_rebuild()
SectionLevel3.model_rebuild()
ColumnsBlock.model_rebuild()
Tab.model_rebuild()
Item2.model_rebuild()
