# generated by datamodel-codegen:
#   filename:  document.json

from __future__ import annotations

from enum import Enum
from typing import Any, Literal, Annotated

from pydantic import AnyUrl, BaseModel, ConfigDict, Field, RootModel, model_validator


class Ulid(RootModel[str]):
    root: str = Field(..., pattern='^[0-9A-HJKMNP-TV-Z]{26}$')
    """
    Crockford base32 ULID
    """


class ImageRef(RootModel[str]):
    root: str = Field(
        ...,
        pattern='^(?:[0-9A-HJKMNP-TV-Z]{26}|[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})$',
    )
    """
    FK to images.id — accepts ULID (legacy seed data) or UUID (uploaded images)
    """


class Slug(RootModel[str]):
    root: str = Field(
        ..., pattern='^[a-z0-9\\uAC00-\\uD7A3][a-z0-9\\uAC00-\\uD7A3-]{0,99}$'
    )
    """
    url-safe identifier (lowercase ASCII, digits, hyphen, Hangul)
    """


class Confidentiality(Enum):
    public = 'public'
    internal = 'internal'
    restricted = 'restricted'


class DocumentMeta(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    division: str = Field(..., min_length=1)
    team: str | None = None
    group: str | None = None
    part: str | None = None
    owners: list[str] = Field(..., min_length=1)
    reviewers: list[str] | None = []
    tags: list[str] = []
    category: str | None = None
    confidentiality: Confidentiality


class Badge(Enum):
    """
    배경/텍스트 컬러로 강조하는 뱃지 종류. neutral=회색.
    """

    success = 'success'
    info = 'info'
    warn = 'warn'
    danger = 'danger'
    neutral = 'neutral'


class InfoboxRich(BaseModel):
    """
    Richer Infobox value — wraps a label with optional link / badge / icon / color hints. Used wherever a plain string isn't enough (예: 상태 뱃지, 담당자 메일 링크).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    text: str
    """
    표시 텍스트.
    """
    href: str | None = None
    """
    링크 URL — 있으면 텍스트가 클릭 가능한 a 태그로 렌더링.
    """
    icon: str | None = None
    """
    선두 이모지 아이콘 (예: 📞 ✉️ 👤).
    """
    badge: Badge | None = None
    """
    배경/텍스트 컬러로 강조하는 뱃지 종류. neutral=회색.
    """
    color: str | None = Field(None, pattern='^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')
    """
    텍스트 색 직접 지정 (badge와 함께 쓰면 badge가 우선).
    """


class Layout(Enum):
    """
    Visual layout for this section's blocks. Drives both the wiki view (block arrangement inside the section) and presentation view (slide template). Defaults to 'stack' (existing behaviour: blocks render top-to-bottom). 'two-col' splits blocks alternately into two columns. 'image-left'/'image-right' put the first ImageBlock on one side and remaining blocks on the other. 'title-only' renders just the section heading (PPT cover style). 'full-bleed' uses the first ImageBlock as a full-width background with subsequent blocks overlaid.
    """

    stack = 'stack'
    two_col = 'two-col'
    image_left = 'image-left'
    image_right = 'image-right'
    title_only = 'title-only'
    full_bleed = 'full-bleed'


class LayoutWidth(RootModel[float]):
    root: float = Field(..., ge=10.0, le=90.0)


class Align(Enum):
    left = 'left'
    center = 'center'
    right = 'right'
    full = 'full'


class Permission(Enum):
    all = 'all'
    editor = 'editor'
    admin = 'admin'


class Level(Enum):
    """
    Heading 블록(heading-4 type)에서 실제 보여줄 단계. 2=큰 제목, 3=중간 제목, 4=작은 제목(기본). 다른 블록 타입에서는 무시됨.
    """

    int_2 = 2
    int_3 = 3
    int_4 = 4


class Audience(Enum):
    """
    이 블록이 노출되는 뷰. 'both'(기본): 위키 + 슬라이드 둘 다. 'wiki-only': 위키에만 (프레젠테이션에서 숨김). 'slide-only': 프레젠테이션에서만 (위키 본문에서는 숨김). 발표용 큰 이미지/스피커 멘트, 또는 위키엔 자세히 적고 슬라이드엔 빼고 싶은 표 등을 분리할 때 사용.
    """

    both = 'both'
    wiki_only = 'wiki-only'
    slide_only = 'slide-only'


class BlockMeta(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    align: Align | None = None
    collapsed: bool | None = None
    locked: bool | None = None
    permission: Permission | None = None
    note: str | None = None
    level: Level | None = None
    """
    Heading 블록(heading-4 type)에서 실제 보여줄 단계. 2=큰 제목, 3=중간 제목, 4=작은 제목(기본). 다른 블록 타입에서는 무시됨.
    """
    width: int | None = Field(None, ge=32, le=4000)
    """
    사용자 지정 블록 너비(px). 미지정 또는 0이면 부모 컨테이너에 맞춤(기존 동작).
    """
    height: int | None = Field(None, ge=32, le=4000)
    """
    사용자 지정 블록 높이(px). 미지정이면 콘텐츠 자동 높이(기존 동작).
    """
    audience: Audience | None = None
    """
    이 블록이 노출되는 뷰. 'both'(기본): 위키 + 슬라이드 둘 다. 'wiki-only': 위키에만 (프레젠테이션에서 숨김). 'slide-only': 프레젠테이션에서만 (위키 본문에서는 숨김). 발표용 큰 이미지/스피커 멘트, 또는 위키엔 자세히 적고 슬라이드엔 빼고 싶은 표 등을 분리할 때 사용.
    """


class ParagraphBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['paragraph']
    id: Ulid
    text: str
    meta: BlockMeta | None = None


class Level1(Enum):
    """
    Visual heading level. Optional — defaults to 4 (smallest). Sub-section heading; the document outline still uses Section nodes for the canonical hierarchy.
    """

    int_2 = 2
    int_3 = 3
    int_4 = 4


class Heading4Block(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['heading-4']
    id: Ulid
    title: str = Field(..., max_length=200)
    level: Level1 | None = None
    """
    Visual heading level. Optional — defaults to 4 (smallest). Sub-section heading; the document outline still uses Section nodes for the canonical hierarchy.
    """
    meta: BlockMeta | None = None


class Style(Enum):
    bullet = 'bullet'
    number = 'number'
    check = 'check'


class ListBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['list']
    id: Ulid
    style: Style
    items: list[str]
    meta: BlockMeta | None = None


class QuoteBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['quote']
    id: Ulid
    text: str
    cite: str | None = None
    meta: BlockMeta | None = None


class Variant(Enum):
    info = 'info'
    warn = 'warn'
    danger = 'danger'
    tip = 'tip'


class CalloutBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['callout']
    id: Ulid
    variant: Variant
    title: str | None = None
    text: str
    meta: BlockMeta | None = None


class CodeBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['code']
    id: Ulid
    language: str
    code: str
    filename: str | None = None
    meta: BlockMeta | None = None


class Display(Enum):
    block = 'block'
    inline = 'inline'


class MathBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['math']
    id: Ulid
    expression: str
    """
    LaTeX (KaTeX 호환)
    """
    display: Display | None = Display.block
    meta: BlockMeta | None = None


class Align1(Enum):
    """
    Per-cell horizontal alignment override (wins over column default).
    """

    left = 'left'
    center = 'center'
    right = 'right'


class Align2(Enum):
    """
    Default cell alignment for this column. dtype=number|percent|currency auto-defaults to right when align is unset.
    """

    left = 'left'
    center = 'center'
    right = 'right'


class Dtype(Enum):
    """
    Column data type. Drives auto-formatting and default alignment.
    """

    text = 'text'
    number = 'number'
    percent = 'percent'
    currency = 'currency'
    date = 'date'


class Column(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    width: str | None = None
    """
    CSS width — '120px' or '15%' or 'auto'.
    """
    align: Align2 | None = None
    """
    Default cell alignment for this column. dtype=number|percent|currency auto-defaults to right when align is unset.
    """
    dtype: Dtype | None = None
    """
    Column data type. Drives auto-formatting and default alignment.
    """
    format: str | None = None
    """
    Format hint. number/percent: decimal places like '2'. currency: ISO code or symbol like 'KRW' / '$'. date: pattern like 'YYYY-MM-DD'.
    """


class Aggregate(Enum):
    field_ = ''
    sum = 'sum'
    avg = 'avg'
    count = 'count'
    min = 'min'
    max = 'max'


class Footer(BaseModel):
    """
    Optional footer row showing per-column aggregates. Computed at render time from `rows` (flat mode) — sparse mode is skipped because merged-cell semantics make column-wise sums ambiguous.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    show: bool | None = None
    label: str | None = None
    """
    Label shown in the first column when no aggregate is set there.
    """
    aggregates: list[Aggregate] | None = None
    """
    Per-column aggregate. '' (empty) skips that column.
    """


class Density(Enum):
    """
    Row padding density. Default 'normal'.
    """

    compact = 'compact'
    normal = 'normal'
    comfortable = 'comfortable'


class BorderStyle(Enum):
    """
    Cell border style. Default 'horizontal'.
    """

    none = 'none'
    horizontal = 'horizontal'
    all = 'all'


class Options(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    sortable: bool | None = None
    """
    Header click sorts asc/desc by that column (flat mode only).
    """
    searchable: bool | None = None
    """
    Show a search box above the table that filters rows (flat mode only).
    """
    density: Density | None = None
    """
    Row padding density. Default 'normal'.
    """
    sticky_first_col: bool | None = Field(None, alias='stickyFirstCol')
    """
    Pin the first column when the table scrolls horizontally.
    """
    row_numbers: bool | None = Field(None, alias='rowNumbers')
    """
    Show 1-based row numbers in a leading column.
    """
    stripe: bool | None = None
    """
    Zebra-striped rows. Default true; set false to disable.
    """
    border_style: BorderStyle | None = Field(None, alias='borderStyle')
    """
    Cell border style. Default 'horizontal'.
    """


class Trend(Enum):
    up = 'up'
    down = 'down'
    flat = 'flat'


class Item(BaseModel):
    label: str
    value: str | float
    delta: str | float | None = None
    trend: Trend | None = None


class KpiCardsBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['kpi-cards']
    id: Ulid
    items: list[Item]
    meta: BlockMeta | None = None


class ChartType(Enum):
    """
    차트 타입. 'xy-line' 은 시리즈마다 자유로운 (x, y) 쌍 — labels 공유 안 함. 두 stress-strain 곡선처럼 시료별 측정점이 다른 데이터를 한 그림에 겹쳐 비교할 때 사용. data.labels 는 무시되고 각 series 의 points: [{x, y}] 가 그려진다.
    """

    line = 'line'
    bar = 'bar'
    pie = 'pie'
    area = 'area'
    radar = 'radar'
    scatter = 'scatter'
    xy_line = 'xy-line'


class Engine(Enum):
    """
    Chart renderer. Default 'recharts' for back-compat; choose 'echarts' for rich interactivity (markPoint / markArea / brush / dataZoom).
    """

    recharts = 'recharts'
    echarts = 'echarts'


class Point(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    x: float
    y: float


class Series(BaseModel):
    name: str
    values: list[float] | None = None
    """
    labels 와 동일 길이의 y 값. chartType=='xy-line' 이면 무시되고 points 사용.
    """
    points: list[Point] | None = None
    """
    자유 (x, y) 쌍. chartType=='xy-line' 에서 사용. 시리즈마다 x 가 다를 수 있어 stress-strain 곡선처럼 측정점이 다른 데이터 비교 가능.
    """
    caption: str | None = None
    """
    시리즈 추가 설명 — hover/legend 에 표시. 캡션은 사용자가 paste 시 헤더에서 추출하거나 직접 입력.
    """


class Data(BaseModel):
    labels: list[str]
    series: list[Series]
    x_axis_label: str | None = Field(None, alias='xAxisLabel')
    """
    x 축 라벨. xy-line 처럼 카테고리가 아닌 연속값일 때 의미. paste 의 'x' 헤더 컬럼명에서 자동 추출 가능.
    """
    y_axis_label: str | None = Field(None, alias='yAxisLabel')
    """
    y 축 라벨. paste 의 'y' 헤더 컬럼명에서 자동 추출 가능.
    """


class KeyPoint(BaseModel):
    label: str
    x_index: int = Field(..., alias='xIndex', ge=0)
    color: str | None = None


class Region(BaseModel):
    label: str
    x_from_index: int = Field(..., alias='xFromIndex', ge=0)
    x_to_index: int = Field(..., alias='xToIndex', ge=0)
    color: str | None = None


class Interactions(BaseModel):
    """
    Friendly knobs for ECharts interactivity that map onto markPoint / markArea / dataZoom without requiring users to write raw EChartsOption.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    key_points: list[KeyPoint] | None = Field(None, alias='keyPoints')
    """
    Highlighted points on the curve (label, x-index, optional color).
    """
    regions: list[Region] | None = None
    """
    Coloured x-range bands (e.g. Elastic / Plastic). xFromIndex / xToIndex are inclusive label indexes.
    """
    show_zoom: bool | None = Field(None, alias='showZoom')
    """
    Inline dataZoom slider under the chart.
    """
    show_crosshair: bool | None = Field(None, alias='showCrosshair')
    """
    Crosshair guides + axis pointers.
    """


class FitType(Enum):
    """
    피팅 모델. P1 은 linear 만, P3 에서 나머지.
    """

    linear = 'linear'
    poly2 = 'poly2'
    poly3 = 'poly3'
    exp = 'exp'
    power = 'power'


class FitRange(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    x_min: float = Field(..., alias='xMin')
    x_max: float = Field(..., alias='xMax')


class Sampling(Enum):
    none = 'none'
    lttb = 'lttb'


class Display1(BaseModel):
    """
    사용자 시각화 토글 상태. 차트 블록과 함께 저장되어 재방문 시 동일 상태 복원. P1 에서 gridOn/xLog/yLog/showFit + 자동 zoom 지원, P2 에서 fitRange/축범위/stats, P3 에서 fitType/도메인 옵션 확장.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    grid_on: bool | None = Field(None, alias='gridOn')
    """
    격자 표시 (기본 true).
    """
    x_log: bool | None = Field(None, alias='xLog')
    """
    x 축 log 스케일.
    """
    y_log: bool | None = Field(None, alias='yLog')
    """
    y 축 log 스케일.
    """
    show_fit: bool | None = Field(None, alias='showFit')
    """
    linear fit + R² markLine 표시.
    """
    x_min: float | None = Field(None, alias='xMin')
    x_max: float | None = Field(None, alias='xMax')
    y_min: float | None = Field(None, alias='yMin')
    y_max: float | None = Field(None, alias='yMax')
    fit_type: FitType | None = Field(None, alias='fitType')
    """
    피팅 모델. P1 은 linear 만, P3 에서 나머지.
    """
    fit_range: FitRange | None = Field(None, alias='fitRange')
    show_stats: bool | None = Field(None, alias='showStats')
    sampling: Sampling | None = None


class ChartBlock(BaseModel):
    """
    Chart block — `engine` selects the renderer. 'recharts' (default) uses our existing simple chart UI; 'echarts' unlocks rich interaction (zoom, brush, hover slope, markPoint annotations, markArea regions). With 'echarts' the data fields below still drive the dataset, but `options` accepts any ECharts EChartsOption fragment that gets merged on top.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['chart']
    id: Ulid
    chart_type: ChartType = Field(..., alias='chartType')
    """
    차트 타입. 'xy-line' 은 시리즈마다 자유로운 (x, y) 쌍 — labels 공유 안 함. 두 stress-strain 곡선처럼 시료별 측정점이 다른 데이터를 한 그림에 겹쳐 비교할 때 사용. data.labels 는 무시되고 각 series 의 points: [{x, y}] 가 그려진다.
    """
    engine: Engine | None = None
    """
    Chart renderer. Default 'recharts' for back-compat; choose 'echarts' for rich interactivity (markPoint / markArea / brush / dataZoom).
    """
    title: str | None = None
    data: Data
    interactions: Interactions | None = None
    """
    Friendly knobs for ECharts interactivity that map onto markPoint / markArea / dataZoom without requiring users to write raw EChartsOption.
    """
    options: dict[str, Any] | None = None
    """
    Raw ECharts EChartsOption fragment, merged after `interactions` so power users can override anything.
    """
    display: Display1 | None = None
    """
    사용자 시각화 토글 상태. 차트 블록과 함께 저장되어 재방문 시 동일 상태 복원. P1 에서 gridOn/xLog/yLog/showFit + 자동 zoom 지원, P2 에서 fitRange/축범위/stats, P3 에서 fitType/도메인 옵션 확장.
    """
    meta: BlockMeta | None = None


class Task(BaseModel):
    name: str
    start: str
    end: str
    progress: float | None = Field(None, ge=0.0, le=100.0)


class GanttBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['gantt']
    id: Ulid
    tasks: list[Task]
    meta: BlockMeta | None = None


class Engine1(Enum):
    mermaid = 'mermaid'
    excalidraw = 'excalidraw'


class FlowBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['flow']
    id: Ulid
    engine: Engine1
    source: str
    """
    Mermaid DSL 또는 excalidraw JSON
    """
    meta: BlockMeta | None = None


class Layout1(Enum):
    tree = 'tree'
    horizontal = 'horizontal'


class OrgChartNode(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    label: str
    role: str | None = None
    children: list[OrgChartNode] | None = Field([], validate_default=True)


class IframeBlock1(BaseModel):
    """
    Embed an external page (`src`) OR an inline self-contained HTML document (`html`). Exactly one MUST be set. The renderer wraps the iframe in a sandbox boundary so the embed can't reach the parent DOM, cookies, or storage; only `allow-scripts` is granted so interactive embeds (charts, calculators) still work.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['iframe']
    id: Ulid
    src: AnyUrl
    """
    사내 화이트리스트 도메인만. `html` 와 동시 사용 금지.
    """
    html: str | None = Field(None, max_length=500000)
    """
    Self-contained HTML document. Rendered via iframe srcdoc + sandbox. Use this for ad-hoc interactive embeds (e.g. canvas-based charts) that don't need a hosting URL. `src` 와 동시 사용 금지.
    """
    title: str | None = None
    height: int | None = Field(None, ge=100, le=2000)
    meta: BlockMeta | None = None

    @model_validator(mode='after')
    def _reject_html_when_src(self):
        # XOR enforcement: src-branch must not also carry html.
        if self.html is not None:
            raise ValueError(
                'iframe block requires exactly one of `src` or `html`'
            )
        return self


class IframeBlock2(BaseModel):
    """
    Embed an external page (`src`) OR an inline self-contained HTML document (`html`). Exactly one MUST be set. The renderer wraps the iframe in a sandbox boundary so the embed can't reach the parent DOM, cookies, or storage; only `allow-scripts` is granted so interactive embeds (charts, calculators) still work.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['iframe']
    id: Ulid
    src: AnyUrl | None = None
    """
    사내 화이트리스트 도메인만. `html` 와 동시 사용 금지.
    """
    html: str = Field(..., max_length=500000)
    """
    Self-contained HTML document. Rendered via iframe srcdoc + sandbox. Use this for ad-hoc interactive embeds (e.g. canvas-based charts) that don't need a hosting URL. `src` 와 동시 사용 금지.
    """
    title: str | None = None
    height: int | None = Field(None, ge=100, le=2000)
    meta: BlockMeta | None = None

    @model_validator(mode='after')
    def _reject_src_when_html(self):
        # XOR enforcement: html-branch must not also carry src.
        if self.src is not None:
            raise ValueError(
                'iframe block requires exactly one of `src` or `html`'
            )
        return self


class IframeBlock(RootModel[IframeBlock1 | IframeBlock2]):
    root: IframeBlock1 | IframeBlock2
    """
    Embed an external page (`src`) OR an inline self-contained HTML document (`html`). Exactly one MUST be set. The renderer wraps the iframe in a sandbox boundary so the embed can't reach the parent DOM, cookies, or storage; only `allow-scripts` is granted so interactive embeds (charts, calculators) still work.
    """


class Provider(Enum):
    intra = 'intra'
    youtube = 'youtube'
    vimeo = 'vimeo'


class VideoBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['video']
    id: Ulid
    url: AnyUrl
    title: str | None = None
    provider: Provider | None = Provider.intra
    autoplay: bool | None = False
    """
    Auto-play on load. Browser autoplay policies may block this when muted=false; treat as a hint.
    """
    controls: bool | None = True
    """
    Show native video controls (play/pause/volume/seek).
    """
    loop: bool | None = False
    """
    Restart automatically when the video ends.
    """
    meta: BlockMeta | None = None


class Width(Enum):
    sm = 'sm'
    md = 'md'
    lg = 'lg'
    full = 'full'


class ImageBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['image']
    id: Ulid
    image_id: ImageRef = Field(..., alias='imageId')
    """
    FK to images.id (ULID or UUID)
    """
    caption: str | None = Field(None, max_length=500)
    alt: str | None = Field(None, max_length=200)
    width: Width | None = Width.md
    link: str | None = None
    """
    외부 URL 또는 위키 slug
    """
    meta: BlockMeta | None = None


class Layout2(Enum):
    grid = 'grid'
    carousel = 'carousel'


class Item1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    image_id: ImageRef = Field(..., alias='imageId')
    caption: str | None = Field(None, max_length=500)
    alt: str | None = Field(None, max_length=200)


class GalleryBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['gallery']
    id: Ulid
    layout: Layout2 = Layout2.grid
    items: list[Item1] = Field(..., min_length=1)
    meta: BlockMeta | None = None


class FileBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['file']
    id: Ulid
    file_id: Ulid = Field(..., alias='fileId')
    name: str
    size: int | None = Field(None, ge=0)
    mime: str | None = None
    meta: BlockMeta | None = None


class PdfBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['pdf']
    id: Ulid
    file_id: str
    """
    FK to files table (mxwp-files); served via /api/v1/files/:file_id/download
    """
    title: str | None = None
    page: int | None = Field(1, ge=1)
    height_px: int | None = Field(600, ge=200, le=4000)
    meta: BlockMeta | None = None


class DocLinkCardBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['doc-link-card']
    id: Ulid
    slug: Slug
    show_summary: bool | None = Field(True, alias='showSummary')
    meta: BlockMeta | None = None


class GlossaryRefBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['glossary-ref']
    id: Ulid
    term: str
    meta: BlockMeta | None = None


class Width1(RootModel[float]):
    root: float = Field(..., ge=5.0, le=95.0)


class Kind(Enum):
    image = 'image'
    table = 'table'
    chart = 'chart'


class FigureIndexBlock(BaseModel):
    """
    Auto-generated table of figures (그림/표/차트 목차). The renderer walks the document and lists every captioned image, table (with caption), and chart (with title), each linked to its anchor. `kinds` controls which lists to render.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['figure-index']
    id: Ulid
    title: str | None = '그림 목차'
    kinds: list[Kind] | None = Field(None, max_length=3, min_length=1)
    """
    Which figure types to include — 'image' (그림), 'table' (표), 'chart' (차트). Order in this array determines section order. Omit for all three.
    """
    meta: BlockMeta | None = None


class Size(Enum):
    sm = 'sm'
    md = 'md'
    lg = 'lg'
    xl = 'xl'


class SpacerBlock(BaseModel):
    """
    Explicit vertical spacer. Default inter-block spacing is tight (8px). Insert a spacer block to add deliberate breathing room. `size` chooses the gap: sm=16px, md=32px (default), lg=64px, xl=128px.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['spacer']
    id: Ulid
    size: Size | None = Size.md
    meta: BlockMeta | None = None


class Render(Enum):
    table = 'table'
    chart = 'chart'
    kpi_cards = 'kpi-cards'


class ChartType1(Enum):
    line = 'line'
    bar = 'bar'
    pie = 'pie'
    area = 'area'
    radar = 'radar'
    scatter = 'scatter'
    xy_line = 'xy-line'


class Engine2(Enum):
    recharts = 'recharts'
    echarts = 'echarts'


class Interactions1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    key_points: list[KeyPoint] | None = Field(None, alias='keyPoints')
    regions: list[Region] | None = None


class ChartOptions(BaseModel):
    """
    Per-document chart styling overrides (only for render=chart). Deep-merged ON TOP of widget-provided defaults — set just the fields you want to change.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    chart_type: ChartType1 | None = Field(None, alias='chartType')
    engine: Engine2 | None = None
    title: str | None = None
    interactions: Interactions1 | None = None
    options: dict[str, Any] | None = None
    """
    Raw ECharts EChartsOption fragment, deep-merged after widget defaults + interactions.
    """


class DataSourceBlock(BaseModel):
    """
    Live data block. Widget response shapes the data; render type fixes the renderer. For render=chart, the widget may include chartType / engine / interactions / options inline; chartOptions on the block deep-merges on top so document authors can override per-doc styling without touching the widget.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['data-source']
    id: Ulid
    endpoint: str = Field(..., pattern='^/api/v1/widgets/')
    params: dict[str, Any] | None = None
    render: Render
    refresh_interval: int | None = Field(None, alias='refreshInterval', ge=30, le=3600)
    chart_options: ChartOptions | None = Field(None, alias='chartOptions')
    """
    Per-document chart styling overrides (only for render=chart). Deep-merged ON TOP of widget-provided defaults — set just the fields you want to change.
    """
    meta: BlockMeta | None = None


class Provider1(Enum):
    grafana = 'grafana'
    tableau = 'tableau'
    superset = 'superset'


class DashboardEmbedBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['dashboard-embed']
    id: Ulid
    provider: Provider1
    panel_id: str = Field(..., alias='panelId')
    params: dict[str, Any] | None = None
    meta: BlockMeta | None = None


class Kind1(Enum):
    number = 'number'
    text = 'text'
    select = 'select'


class Input(BaseModel):
    name: str
    label: str
    default: str | float | bool | None = None
    kind: Kind1 | None = Kind1.number


class CalculatorBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['calculator']
    id: Ulid
    inputs: list[Input]
    formula: str
    """
    안전한 표현식 (mathjs 등)
    """
    label: str | None = None
    meta: BlockMeta | None = None


class Viewbox(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    w: int = Field(..., ge=100, le=4000)
    h: int = Field(..., ge=100, le=4000)


class Point1(RootModel[list[float]]):
    root: list[float] = Field(..., max_length=2, min_length=2)


class WhiteboardElement1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['stroke']
    id: str
    points: list[Point1]
    stroke: str
    stroke_width: float = Field(..., alias='strokeWidth', ge=1.0, le=32.0)


class Shape(Enum):
    rect = 'rect'
    ellipse = 'ellipse'
    line = 'line'
    arrow = 'arrow'


class WhiteboardElement2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['shape']
    id: str
    shape: Shape
    x: float
    y: float
    w: float
    h: float
    stroke: str
    stroke_width: float = Field(..., alias='strokeWidth', ge=1.0, le=32.0)
    fill: str | None = None


class WhiteboardElement3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['text']
    id: str
    x: float
    y: float
    text: str
    font_size: float = Field(..., alias='fontSize', ge=8.0, le=96.0)
    color: str


class WhiteboardElement(
    RootModel[WhiteboardElement1 | WhiteboardElement2 | WhiteboardElement3]
):
    root: WhiteboardElement1 | WhiteboardElement2 | WhiteboardElement3


class Kind2(Enum):
    text = 'text'
    long_text = 'long-text'
    email = 'email'
    number = 'number'
    select = 'select'
    multi_select = 'multi-select'
    checkbox = 'checkbox'
    rating_5 = 'rating-5'
    date = 'date'


class FormQuestion(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    kind: Kind2
    label: str
    required: bool | None = False
    placeholder: str | None = None
    options: list[str] | None = None


class Kind3(Enum):
    single_choice = 'single-choice'
    multi_choice = 'multi-choice'
    true_false = 'true-false'
    short_text = 'short-text'


class QuizQuestion(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    kind: Kind3
    label: str
    options: list[str] | None = None
    correct: str | list[str] | bool
    explanation: str | None = None
    points: int | None = Field(1, ge=0)


class From(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    x: float
    y: float


class To(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    x: float
    y: float


class AnnotationElement1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['arrow']
    id: str
    from_: From = Field(..., alias='from')
    to: To
    color: str
    label: str | None = None


class AnnotationElement2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['rect']
    id: str
    x: float
    y: float
    w: float
    h: float
    color: str
    label: str | None = None


class Anchor(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    x: float
    y: float


class AnnotationElement3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['callout']
    id: str
    x: float
    y: float
    anchor: Anchor | None = None
    label: str
    """
    Annotation label (was `text` pre-pass-2). BE normaliser rewrites legacy `text` → `label` on read.
    """
    color: str


class AnnotationElement4(BaseModel):
    """
    이미지 위 자유 위치 multi-line 텍스트 박스. callout(짧은 라벨) 과 달리 박스 크기 (w, h) 와 줄바꿈을 가진 본문성 주석. 이미지의 특정 영역을 설명하는 글을 직접 얹는 용도.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['textbox']
    id: str
    x: float
    y: float
    w: float
    h: float
    text: str
    """
    Multi-line plain text. \\n 으로 줄 구분.
    """
    color: str
    """
    텍스트 색.
    """
    font_size: float | None = Field(None, alias='fontSize')
    """
    정규화 좌표계 기준 글자 크기 (기본 0.025). 좌표가 0-1 이라 일반적으로 0.015~0.06.
    """
    bg: str | None = None
    """
    박스 배경색 (선택). 미지정 시 반투명 흰색 폴백.
    """


class AnnotationElement(
    RootModel[
        AnnotationElement1
        | AnnotationElement2
        | AnnotationElement3
        | AnnotationElement4
    ]
):
    root: (
        AnnotationElement1
        | AnnotationElement2
        | AnnotationElement3
        | AnnotationElement4
    )


class Options1(BaseModel):
    """
    Visual rendering options. All fields optional with sensible defaults.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    stripe: bool | None = None
    """
    Zebra-striped data rows for readability. Default true; set false to disable. Header row is unaffected.
    """


class SpreadsheetBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['spreadsheet']
    id: Ulid
    title: str | None = None
    cols: int = Field(6, ge=1, le=26)
    rows: int = Field(10, ge=1, le=200)
    headers: list[str] | None = None
    cells: dict[str, str]
    """
    Sparse map of cell-ref → raw cell input (e.g. {'A1':'42', 'B2':'=SUM(A1:A10)'})
    """
    options: Options1 | None = None
    """
    Visual rendering options. All fields optional with sensible defaults.
    """
    meta: BlockMeta | None = None


class Style1(Enum):
    """
    Citation style label (numeric / alphabetic / author-year). Currently informational — the FE renders ordered list either way.
    """

    numeric = 'numeric'
    alphabetic = 'alphabetic'
    author_year = 'author-year'


class Entry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    key: str | None = Field(None, max_length=60, pattern='^[A-Za-z0-9_-]+$')
    """
    Optional citation key used by [[cite:KEY]] inline references. Alphanumeric / hyphen / underscore.
    """
    text: str = Field(..., max_length=2000, min_length=1)
    """
    Formatted reference body — e.g. 'Smith, J. (2020). Foo bar. Journal of X, 3(2), 14-22.'
    """
    url: str | None = Field(None, max_length=1000)
    """
    Optional canonical URL (DOI, journal page).
    """


class BibliographyBlock(BaseModel):
    """
    Reference list (참고문헌). Citations elsewhere in the document use the [[cite:KEY]] inline syntax to anchor-link into entries here. Most often produced by the DOCX importer when it sees a 'References' / '참고문헌' / 'Bibliography' heading.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['bibliography']
    id: Ulid
    title: str | None = Field(None, max_length=200)
    """
    Optional override for the block heading. Defaults to '참고문헌' in the FE renderer.
    """
    style: Style1 | None = None
    """
    Citation style label (numeric / alphabetic / author-year). Currently informational — the FE renders ordered list either way.
    """
    entries: list[Entry] = Field(..., min_length=1)
    meta: BlockMeta | None = None


class RelatedDoc(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    slug: Slug
    relation: str = Field(..., examples=['참고', '선행', '후속', '유사'])


class GlossaryItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    term: str = Field(..., min_length=1)
    definition: str = Field(..., min_length=1)


class Type(Enum):
    internal = 'internal'
    external = 'external'


class Reference(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Type
    label: str
    url: AnyUrl | None = None


class Infobox(RootModel[dict[str, str | list[str] | InfoboxRich | list[InfoboxRich]]]):
    """
    우상단 정보 박스. 키=라벨, 값=문자열, 문자열 배열, 또는 풍부한 표현(링크/뱃지/아이콘)을 위한 InfoboxRich 객체. 기존 문자열 형태는 그대로 호환.
    """

    root: dict[str, str | list[str] | InfoboxRich | list[InfoboxRich]]


class CellBlock(RootModel[ParagraphBlock | ImageBlock | ListBlock]):
    root: ParagraphBlock | ImageBlock | ListBlock
    """
    Block subset allowed inside a TableBlock cell's `blocks` array. Intentionally narrow to keep table cell rendering tractable — only paragraph/image/list.
    """


class Cell(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    r: int = Field(..., ge=0)
    c: int = Field(..., ge=0)
    row_span: int | None = Field(None, alias='rowSpan', ge=1)
    col_span: int | None = Field(None, alias='colSpan', ge=1)
    text: str | None = None
    blocks: list[CellBlock] | None = Field(None, min_length=1)
    """
    Mixed-content cell payload. When present, renderers ignore `text` and lay out these blocks inside the cell. Restricted to paragraph/image/list to keep cell layout tractable — tables-in-tables and callouts-in-cells are intentionally out of scope.
    """
    header: bool | None = None
    """
    True for header-row cells (rendered as <th>).
    """
    align: Align1 | None = None
    """
    Per-cell horizontal alignment override (wins over column default).
    """
    bg: str | None = Field(None, pattern='^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')
    """
    Cell background color (CSS hex).
    """
    bold: bool | None = None
    """
    Bold text in this cell.
    """
    color: str | None = Field(None, pattern='^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')
    """
    Cell text color (CSS hex).
    """


class TableBlock(BaseModel):
    """
    Table block. Two layout modes: flat (`headers` + `rows`, the common case) and sparse (`cells`, used whenever cells are merged or styled per-cell). The renderer prefers `cells` when present. Optional `columns` carries per-column metadata (width / align / dtype / format) that applies to BOTH modes — column index is well-defined in either layout.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['table']
    id: Ulid
    caption: str | None = Field(None, max_length=500)
    """
    Optional caption rendered below the table; participates in auto-numbering ('표 N: ...').
    """
    headers: list[str]
    rows: list[list[str]]
    cells: list[Cell] | None = None
    """
    Optional sparse cell list for tables with merged or styled cells (DOCX gridSpan/vMerge round-trip + per-cell style overrides). When present, the renderer ignores headers/rows and lays out from this list. Each cell occupies (r..r+rowSpan-1) × (c..c+colSpan-1); covered slots have no entry. r/c are 0-indexed; the first row of a header-mode table is the header row. A cell carries content via either `text` (plain string, the common case) or `blocks` (mixed content — paragraph/image/list). Exactly one of the two MUST be set; empty cell ⇒ text=''.
    """
    columns: list[Column] | None = None
    """
    Optional per-column metadata. Index matches column index in both flat and sparse layouts. Missing entries fall back to defaults (left-align, text dtype, auto width).
    """
    footer: Footer | None = None
    """
    Optional footer row showing per-column aggregates. Computed at render time from `rows` (flat mode) — sparse mode is skipped because merged-cell semantics make column-wise sums ambiguous.
    """
    options: Options | None = None
    meta: BlockMeta | None = None


class OrgChartBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['org-chart']
    id: Ulid
    root: OrgChartNode
    layout: Layout1 | None = Layout1.tree
    meta: BlockMeta | None = None


class WhiteboardBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['whiteboard']
    id: Ulid
    title: str | None = None
    viewbox: Viewbox
    elements: list[WhiteboardElement]
    meta: BlockMeta | None = None


class FormBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['form']
    id: Ulid
    title: str | None = None
    description: str | None = None
    questions: list[FormQuestion] = Field(..., min_length=1)
    submit_label: str | None = '제출'
    thanks_message: str | None = '응답해 주셔서 감사합니다.'
    allow_multiple_responses: bool | None = False
    meta: BlockMeta | None = None


class QuizBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['quiz']
    id: Ulid
    title: str | None = None
    description: str | None = None
    questions: list[QuizQuestion] = Field(..., min_length=1)
    passing_score: int | None = Field(70, ge=0, le=100)
    shuffle: bool | None = False
    max_attempts: int | None = Field(0, ge=0)
    show_answers_after: bool | None = True
    meta: BlockMeta | None = None


class ImageAnnotationBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['image-annotation']
    id: Ulid
    image_id: str = Field(..., alias='imageId')
    """
    FK to images table (mxwp-images). Camel-case to match ImageBlock; BE normalizes legacy 'image_id' on read.
    """
    caption: str | None = None
    annotations: list[AnnotationElement]
    meta: BlockMeta | None = None


class DocumentjsonV10(BaseModel):
    """
    MX White Paper 단일 진실 공급원(SSOT). Section 트리(level 1~3) + Block 배열 본문. PROJECT_PLAN.md / Plan / Design / Do 문서의 모든 데이터 모델 참조처.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: Literal['1.0']
    id: Ulid
    slug: Slug
    title: str = Field(..., max_length=200, min_length=1)
    summary: str | None = Field(None, max_length=500)
    metadata: DocumentMeta
    infobox: Infobox | None = None
    sections: list[Section]
    """
    최상위 섹션은 반드시 level=1 (BE 가 검증). 자식 섹션은 부모 level+1.
    """
    related_documents: list[RelatedDoc] | None = Field([], validate_default=True)
    glossary: list[GlossaryItem] | None = Field([], validate_default=True)
    references: list[Reference] | None = Field([], validate_default=True)
    see_also: list[Slug] | None = Field([], validate_default=True)
    variables: dict[str, str] | None = None
    """
    Map of variable names → fill-in strings used to substitute {{var}} tokens at render time.
    """
    custom_css: str | None = Field(None, max_length=10000)
    """
    Optional CSS injected into the doc's render. Sandboxed: no <script>, no expression(), no url(javascript:), no @import, no behavior:.
    """


class Section(BaseModel):
    """
    Document outline node. Recursive — `subsections` is another Section[]. Top-level entries MUST have level=1; child level = parent.level + 1 (enforced by the BE renumber/validate pass). The visual rendering caps at HTML <h6> (level 5+ all render as h6) but schema-wise depth is unbounded.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: Ulid
    number: str | None = Field(None, pattern='^\\d+(?:\\.\\d+)*$')
    """
    1.2.3.4… dotted ordinal recomputed by the BE on every save.
    """
    level: int = Field(..., ge=1)
    """
    1-based depth. BE rejects values that don't match the tree position.
    """
    title: str = Field(..., max_length=200, min_length=1)
    layout: Layout | None = None
    """
    Visual layout for this section's blocks. Drives both the wiki view (block arrangement inside the section) and presentation view (slide template). Defaults to 'stack' (existing behaviour: blocks render top-to-bottom). 'two-col' splits blocks alternately into two columns. 'image-left'/'image-right' put the first ImageBlock on one side and remaining blocks on the other. 'title-only' renders just the section heading (PPT cover style). 'full-bleed' uses the first ImageBlock as a full-width background with subsequent blocks overlaid.
    """
    layout_widths: list[LayoutWidth] | None = Field(
        None, alias='layoutWidths', max_length=2, min_length=2
    )
    """
    Per-pane percentage widths for two-pane layouts (two-col / image-left / image-right). Length MUST equal 2 when present, each value 10..90, sum SHOULD equal 100 (FE normalises). Ignored for stack / title-only / full-bleed. Omit for equal 50/50 split.
    """
    blocks: list[Block]
    subsections: list[Section] | None = Field([], validate_default=True)


class ColumnsBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['columns']
    id: Ulid
    columns: list[list[Block]] = Field(..., max_length=4, min_length=2)
    widths: list[Width1] | None = Field(None, max_length=4, min_length=2)
    """
    Optional per-column widths as percentages of the row. Length MUST equal columns.length when present, each value 5..95, and the sum SHOULD equal 100 (server normalises). Omit for equal split.
    """
    meta: BlockMeta | None = None


class Tab(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    label: str
    blocks: list[Block]


class TabsBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['tabs']
    id: Ulid
    tabs: list[Tab] = Field(..., min_length=1)
    meta: BlockMeta | None = None


class Item2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    label: str
    blocks: list[Block]


class AccordionBlock(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['accordion']
    id: Ulid
    items: list[Item2] = Field(..., min_length=1)
    meta: BlockMeta | None = None


class Block(
    RootModel[
        Annotated[
        ParagraphBlock
        | Heading4Block
        | ListBlock
        | QuoteBlock
        | CalloutBlock
        | CodeBlock
        | MathBlock
        | TableBlock
        | KpiCardsBlock
        | ChartBlock
        | GanttBlock
        | FlowBlock
        | OrgChartBlock
        | IframeBlock
        | VideoBlock
        | ImageBlock
        | GalleryBlock
        | FileBlock
        | DocLinkCardBlock
        | GlossaryRefBlock
        | ColumnsBlock
        | TabsBlock
        | AccordionBlock
        | DataSourceBlock
        | DashboardEmbedBlock
        | CalculatorBlock
        | WhiteboardBlock
        | FormBlock
        | PdfBlock
        | QuizBlock
        | ImageAnnotationBlock
        | SpreadsheetBlock
        | BibliographyBlock
        | SpacerBlock
        | FigureIndexBlock
        ,
        Field(discriminator='type'),
    ]
    ]
):
    root: (
        ParagraphBlock
        | Heading4Block
        | ListBlock
        | QuoteBlock
        | CalloutBlock
        | CodeBlock
        | MathBlock
        | TableBlock
        | KpiCardsBlock
        | ChartBlock
        | GanttBlock
        | FlowBlock
        | OrgChartBlock
        | IframeBlock
        | VideoBlock
        | ImageBlock
        | GalleryBlock
        | FileBlock
        | DocLinkCardBlock
        | GlossaryRefBlock
        | ColumnsBlock
        | TabsBlock
        | AccordionBlock
        | DataSourceBlock
        | DashboardEmbedBlock
        | CalculatorBlock
        | WhiteboardBlock
        | FormBlock
        | PdfBlock
        | QuizBlock
        | ImageAnnotationBlock
        | SpreadsheetBlock
        | BibliographyBlock
        | SpacerBlock
        | FigureIndexBlock
    )


OrgChartNode.model_rebuild()
DocumentjsonV10.model_rebuild()
Section.model_rebuild()
ColumnsBlock.model_rebuild()
Tab.model_rebuild()
Item2.model_rebuild()
