/**
 * Visual regression PoC — darkmode coverage.
 *
 * Captures a single sample document page in both light and dark themes
 * and compares against baseline PNGs stored under `__screenshots__/`.
 * Generated by the `visual-regression` PDCA cycle (2026-05-24).
 *
 * Re-baseline locally with:
 *   pnpm playwright test tests/e2e/visual-darkmode.spec.ts --update-snapshots
 *
 * The page uses `white-paper-realtime-edit-design` which contains chart,
 * gantt, flow (mermaid), and several block surfaces — exercising every
 * darkmode integration path landed in chart-darkmode, gantt-darkmode,
 * orgchart-darkmode, block-darkmode-batch, and chart-libs-darkmode.
 */
import { test, expect } from '@playwright/test'
import { loginAsAdmin } from './helpers'

const SAMPLE_SLUG = 'white-paper-realtime-edit-design'

test.describe('visual: darkmode regression PoC', () => {
  test.beforeEach(async ({ page }) => {
    await loginAsAdmin(page)
  })

  test('light mode renders the sample doc consistently', async ({ page }) => {
    await page.addInitScript(() => {
      document.documentElement.classList.remove('dark')
      document.documentElement.removeAttribute('data-theme')
    })
    await page.goto(`/docs/${encodeURIComponent(SAMPLE_SLUG)}`)
    // Wait for mermaid + charts to render. The article is the doc body.
    await page.waitForSelector('article', { timeout: 15_000 })
    // Allow a generous settle window for async chart libs (echarts,
    // mermaid, recharts ResponsiveContainer measure).
    await page.waitForTimeout(2_000)
    await expect(page).toHaveScreenshot('doc-light.png', {
      fullPage: true,
      maxDiffPixelRatio: 0.02,
      animations: 'disabled',
    })
  })

  test('dark mode renders the sample doc consistently', async ({ page }) => {
    await page.addInitScript(() => {
      document.documentElement.classList.add('dark')
      document.documentElement.setAttribute('data-theme', 'dark')
    })
    await page.goto(`/docs/${encodeURIComponent(SAMPLE_SLUG)}`)
    await page.waitForSelector('article', { timeout: 15_000 })
    await page.waitForTimeout(2_000)
    await expect(page).toHaveScreenshot('doc-dark.png', {
      fullPage: true,
      maxDiffPixelRatio: 0.02,
      animations: 'disabled',
    })
  })
})
